/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WalletsItemRequestBuilder, WalletsItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /wallets
 */
export interface WalletsRequestBuilder extends BaseRequestBuilder<WalletsRequestBuilder> {
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * Gets an item from the leadping.wallets.item collection
     * @param id The ID of the wallet to retrieve.
     * @returns {WalletsItemRequestBuilder}
     */
     byId(id: string) : WalletsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WalletsRequestBuilderUriTemplate = "{+baseurl}/wallets";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WalletsRequestBuilderNavigationMetadata: Record<Exclude<keyof WalletsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: WalletsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
