/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithSmsEventItemRequestBuilder, WithSmsEventItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { SendRequestBuilderRequestsMetadata, type SendRequestBuilder } from './send/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sms
 */
export interface SmsRequestBuilder extends BaseRequestBuilder<SmsRequestBuilder> {
    /**
     * The send property
     */
    get send(): SendRequestBuilder;
    /**
     * Gets an item from the leadping.sms.item collection
     * @param smsEventId The sms event identifier.
     * @returns {WithSmsEventItemRequestBuilder}
     */
     bySmsEventId(smsEventId: string) : WithSmsEventItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SmsRequestBuilderUriTemplate = "{+baseurl}/sms";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SmsRequestBuilderNavigationMetadata: Record<Exclude<keyof SmsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySmsEventId: {
        navigationMetadata: WithSmsEventItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["smsEventId"],
    },
    send: {
        requestsMetadata: SendRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
