/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfNotificationTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfNotificationTableRow, serializeRequestDataOptions, type PagedResultOfNotificationTableRow, type ProblemDetails, type RequestDataOptions } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications/me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * Lists current-user notifications with paging, sorting, and filters for operational alerts, announcements, and follow-up updates.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfNotificationTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfNotificationTableRow | undefined>;
    /**
     * Lists current-user notifications with paging, sorting, and filters for operational alerts, announcements, and follow-up updates.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/notifications/me";
/**
 * Metadata for all the requests in the request builder.
 */
export const MeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfNotificationTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
