/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AnnouncementsRequestBuilderRequestsMetadata, type AnnouncementsRequestBuilder } from './announcements/index.js';
// @ts-ignore
import { NotificationsItemRequestBuilderNavigationMetadata, NotificationsItemRequestBuilderRequestsMetadata, type NotificationsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { MarkAllReadRequestBuilderRequestsMetadata, type MarkAllReadRequestBuilder } from './markAllRead/index.js';
// @ts-ignore
import { MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { type UnreadCountRequestBuilder, UnreadCountRequestBuilderRequestsMetadata } from './unreadCount/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications
 */
export interface NotificationsRequestBuilder extends BaseRequestBuilder<NotificationsRequestBuilder> {
    /**
     * The announcements property
     */
    get announcements(): AnnouncementsRequestBuilder;
    /**
     * The markAllRead property
     */
    get markAllRead(): MarkAllReadRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * The unreadCount property
     */
    get unreadCount(): UnreadCountRequestBuilder;
    /**
     * Gets an item from the leadping.notifications.item collection
     * @param id The notification ID.
     * @returns {NotificationsItemRequestBuilder}
     */
     byId(id: string) : NotificationsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const NotificationsRequestBuilderUriTemplate = "{+baseurl}/notifications";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NotificationsRequestBuilderNavigationMetadata: Record<Exclude<keyof NotificationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: NotificationsItemRequestBuilderRequestsMetadata,
        navigationMetadata: NotificationsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    announcements: {
        requestsMetadata: AnnouncementsRequestBuilderRequestsMetadata,
    },
    markAllRead: {
        requestsMetadata: MarkAllReadRequestBuilderRequestsMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
    },
    unreadCount: {
        requestsMetadata: UnreadCountRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
