/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics
 */
export interface AnalyticsRequestBuilder extends BaseRequestBuilder<AnalyticsRequestBuilder> {
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AnalyticsRequestBuilderUriTemplate = "{+baseurl}/analytics";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnalyticsRequestBuilderNavigationMetadata: Record<Exclude<keyof AnalyticsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
