/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithExportItemRequestBuilder, WithExportItemRequestBuilderNavigationMetadata, WithExportItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /reports/exports
 */
export interface ExportsRequestBuilder extends BaseRequestBuilder<ExportsRequestBuilder> {
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
    /**
     * Gets an item from the leadping.reports.exports.item collection
     * @param exportId Unique identifier of the item
     * @returns {WithExportItemRequestBuilder}
     */
     byExportId(exportId: string) : WithExportItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ExportsRequestBuilderUriTemplate = "{+baseurl}/reports/exports";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExportsRequestBuilderNavigationMetadata: Record<Exclude<keyof ExportsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byExportId: {
        requestsMetadata: WithExportItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithExportItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["exportId"],
    },
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
