/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MarkReadRequestBuilderRequestsMetadata, type MarkReadRequestBuilder } from './markRead/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /conversations/{id}
 */
export interface ConversationsItemRequestBuilder extends BaseRequestBuilder<ConversationsItemRequestBuilder> {
    /**
     * The markRead property
     */
    get markRead(): MarkReadRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConversationsItemRequestBuilderUriTemplate = "{+baseurl}/conversations/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    markRead: {
        requestsMetadata: MarkReadRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
