/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOrganizationApiKeyIssueResponseFromDiscriminatorValue, createOrganizationApiKeyPreviewResponseFromDiscriminatorValue, createOrganizationApiKeyRevokeResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeOrganizationApiKeyIssueResponse, serializeOrganizationApiKeyRequest, type OrganizationApiKeyIssueResponse, type OrganizationApiKeyPreviewResponse, type OrganizationApiKeyRequest, type OrganizationApiKeyRevokeResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizations/api-keys/{id}
 */
export interface ApiKeysItemRequestBuilder extends BaseRequestBuilder<ApiKeysItemRequestBuilder> {
    /**
     * Confirmation that identifies the revoked key.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrganizationApiKeyRevokeResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationApiKeyRevokeResponse | undefined>;
    /**
     * Returns the API key row with a safe token preview.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrganizationApiKeyPreviewResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationApiKeyPreviewResponse | undefined>;
    /**
     * The one-time API token and safe key detail row.
     * @param body Defines the display name and access configuration for a new Leadping organization API key.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrganizationApiKeyIssueResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: OrganizationApiKeyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationApiKeyIssueResponse | undefined>;
    /**
     * Confirmation that identifies the revoked key.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Returns the API key row with a safe token preview.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * The one-time API token and safe key detail row.
     * @param body Defines the display name and access configuration for a new Leadping organization API key.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OrganizationApiKeyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ApiKeysItemRequestBuilderUriTemplate = "{+baseurl}/organizations/api-keys/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ApiKeysItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ApiKeysItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrganizationApiKeyRevokeResponseFromDiscriminatorValue,
    },
    get: {
        uriTemplate: ApiKeysItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrganizationApiKeyPreviewResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ApiKeysItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrganizationApiKeyIssueResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOrganizationApiKeyRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
