/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { NotesRequestBuilderRequestsMetadata, type NotesRequestBuilder } from './notes/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses/me/10dlc
 */
export interface OneZerodlcRequestBuilder extends BaseRequestBuilder<OneZerodlcRequestBuilder> {
    /**
     * The notes property
     */
    get notes(): NotesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OneZerodlcRequestBuilderUriTemplate = "{+baseurl}/businesses/me/10dlc";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OneZerodlcRequestBuilderNavigationMetadata: Record<Exclude<keyof OneZerodlcRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    notes: {
        requestsMetadata: NotesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
