/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithOrganizationItemRequestBuilder, WithOrganizationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/organizations
 */
export interface OrganizationsRequestBuilder extends BaseRequestBuilder<OrganizationsRequestBuilder> {
    /**
     * Gets an item from the leadping.events.organizations.item collection
     * @param organizationId The organization identifier.
     * @returns {WithOrganizationItemRequestBuilder}
     */
     byOrganizationId(organizationId: string) : WithOrganizationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrganizationsRequestBuilderUriTemplate = "{+baseurl}/events/organizations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrganizationsRequestBuilderNavigationMetadata: Record<Exclude<keyof OrganizationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOrganizationId: {
        requestsMetadata: WithOrganizationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["organizationId"],
    },
};
/* tslint:enable */
/* eslint-enable */
