/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCustomerAnalyticsResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type CustomerAnalyticsResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics/my
 */
export interface MyRequestBuilder extends BaseRequestBuilder<MyRequestBuilder> {
    /**
     * Returns current-business analytics for lead communication, including event volume, response metrics, and date-range filtering.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CustomerAnalyticsResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<MyRequestBuilderGetQueryParameters> | undefined) : Promise<CustomerAnalyticsResponse | undefined>;
    /**
     * Returns current-business analytics for lead communication, including event volume, response metrics, and date-range filtering.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MyRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns current-business analytics for lead communication, including event volume, response metrics, and date-range filtering.
 */
export interface MyRequestBuilderGetQueryParameters {
    days?: number;
    endAt?: Date;
    startAt?: Date;
}
/**
 * Uri template for the request builder.
 */
export const MyRequestBuilderUriTemplate = "{+baseurl}/analytics/my{?days*,endAt*,startAt*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MyRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCustomerAnalyticsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
