/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { InvitationsRequestBuilderNavigationMetadata, type InvitationsRequestBuilder } from './invitations/index.js';
// @ts-ignore
import { MeRequestBuilderNavigationMetadata, MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses
 */
export interface BusinessesRequestBuilder extends BaseRequestBuilder<BusinessesRequestBuilder> {
    /**
     * The invitations property
     */
    get invitations(): InvitationsRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BusinessesRequestBuilderUriTemplate = "{+baseurl}/businesses";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BusinessesRequestBuilderNavigationMetadata: Record<Exclude<keyof BusinessesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    invitations: {
        navigationMetadata: InvitationsRequestBuilderNavigationMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
        navigationMetadata: MeRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
