/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUserResponseFromDiscriminatorValue, type ProblemDetails, type UserResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/me/last-login
 */
export interface LastLoginRequestBuilder extends BaseRequestBuilder<LastLoginRequestBuilder> {
    /**
     * Records a successful sign-in for the current user, updating login metadata used for auditing and account events.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserResponse>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserResponse | undefined>;
    /**
     * Records a successful sign-in for the current user, updating login metadata used for auditing and account events.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LastLoginRequestBuilderUriTemplate = "{+baseurl}/users/me/last-login";
/**
 * Metadata for all the requests in the request builder.
 */
export const LastLoginRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LastLoginRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
