/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /usage/summary
 */
export interface SummaryRequestBuilder extends BaseRequestBuilder<SummaryRequestBuilder> {
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SummaryRequestBuilderUriTemplate = "{+baseurl}/usage/summary";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SummaryRequestBuilderNavigationMetadata: Record<Exclude<keyof SummaryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
