/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createStripeInvoiceResponseFromDiscriminatorValue, type ProblemDetails, type StripeInvoiceResponse } from '../../models/index.js';
// @ts-ignore
import { type WithInvoiceItemRequestBuilder, WithInvoiceItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payment-methods/invoices
 */
export interface InvoicesRequestBuilder extends BaseRequestBuilder<InvoicesRequestBuilder> {
    /**
     * Gets an item from the leadping.paymentMethods.invoices.item collection
     * @param invoiceId The Stripe invoice identifier whose PDF should be accessed.
     * @returns {WithInvoiceItemRequestBuilder}
     */
     byInvoiceId(invoiceId: string) : WithInvoiceItemRequestBuilder;
    /**
     * Returns the current organization's Stripe invoices with their amounts, payment status, billing period, and hosted invoice details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StripeInvoiceResponse[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<StripeInvoiceResponse[] | undefined>;
    /**
     * Returns the current organization's Stripe invoices with their amounts, payment status, billing period, and hosted invoice details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InvoicesRequestBuilderUriTemplate = "{+baseurl}/payment-methods/invoices";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InvoicesRequestBuilderNavigationMetadata: Record<Exclude<keyof InvoicesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byInvoiceId: {
        navigationMetadata: WithInvoiceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["invoiceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InvoicesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InvoicesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createStripeInvoiceResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
