/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUserDataExportResponseFromDiscriminatorValue, type ProblemDetails, type UserDataExportResponse } from '../../../models/index.js';
// @ts-ignore
import { DownloadRequestBuilderRequestsMetadata, type DownloadRequestBuilder } from './download/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /reports/exports/{exportId}
 */
export interface WithExportItemRequestBuilder extends BaseRequestBuilder<WithExportItemRequestBuilder> {
    /**
     * The download property
     */
    get download(): DownloadRequestBuilder;
    /**
     * Returns the status and metadata for one current-user data export, including readiness, expiration, and download availability.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserDataExportResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserDataExportResponse | undefined>;
    /**
     * Returns the status and metadata for one current-user data export, including readiness, expiration, and download availability.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithExportItemRequestBuilderUriTemplate = "{+baseurl}/reports/exports/{exportId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithExportItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithExportItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    download: {
        requestsMetadata: DownloadRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithExportItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithExportItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserDataExportResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
