/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AnalyticsRequestBuilderNavigationMetadata, type AnalyticsRequestBuilder } from './analytics/index.js';
// @ts-ignore
import { AutomationsRequestBuilderNavigationMetadata, AutomationsRequestBuilderRequestsMetadata, type AutomationsRequestBuilder } from './automations/index.js';
// @ts-ignore
import { BusinessesRequestBuilderNavigationMetadata, type BusinessesRequestBuilder } from './businesses/index.js';
// @ts-ignore
import { ContactRequestBuilderRequestsMetadata, type ContactRequestBuilder } from './contact/index.js';
// @ts-ignore
import { ConversationsRequestBuilderNavigationMetadata, type ConversationsRequestBuilder } from './conversations/index.js';
// @ts-ignore
import { DispositionsRequestBuilderNavigationMetadata, DispositionsRequestBuilderRequestsMetadata, type DispositionsRequestBuilder } from './dispositions/index.js';
// @ts-ignore
import { EventsRequestBuilderNavigationMetadata, type EventsRequestBuilder } from './events/index.js';
// @ts-ignore
import { FeedbackRequestBuilderRequestsMetadata, type FeedbackRequestBuilder } from './feedback/index.js';
// @ts-ignore
import { LeadsRequestBuilderNavigationMetadata, LeadsRequestBuilderRequestsMetadata, type LeadsRequestBuilder } from './leads/index.js';
// @ts-ignore
import { LeadStatusesRequestBuilderNavigationMetadata, LeadStatusesRequestBuilderRequestsMetadata, type LeadStatusesRequestBuilder } from './leadStatuses/index.js';
// @ts-ignore
import { NotificationsRequestBuilderNavigationMetadata, type NotificationsRequestBuilder } from './notifications/index.js';
// @ts-ignore
import { OutboundRequestBuilderNavigationMetadata, type OutboundRequestBuilder } from './outbound/index.js';
// @ts-ignore
import { PaymentMethodsRequestBuilderNavigationMetadata, PaymentMethodsRequestBuilderRequestsMetadata, type PaymentMethodsRequestBuilder } from './paymentMethods/index.js';
// @ts-ignore
import { PhoneCallRequestBuilderNavigationMetadata, type PhoneCallRequestBuilder } from './phoneCall/index.js';
// @ts-ignore
import { PhoneNumbersRequestBuilderNavigationMetadata, PhoneNumbersRequestBuilderRequestsMetadata, type PhoneNumbersRequestBuilder } from './phoneNumbers/index.js';
// @ts-ignore
import { ReportsRequestBuilderNavigationMetadata, type ReportsRequestBuilder } from './reports/index.js';
// @ts-ignore
import { SmsRequestBuilderNavigationMetadata, type SmsRequestBuilder } from './sms/index.js';
// @ts-ignore
import { SourcesRequestBuilderNavigationMetadata, SourcesRequestBuilderRequestsMetadata, type SourcesRequestBuilder } from './sources/index.js';
// @ts-ignore
import { SuppressionsRequestBuilderNavigationMetadata, SuppressionsRequestBuilderRequestsMetadata, type SuppressionsRequestBuilder } from './suppressions/index.js';
// @ts-ignore
import { TagsRequestBuilderNavigationMetadata, TagsRequestBuilderRequestsMetadata, type TagsRequestBuilder } from './tags/index.js';
// @ts-ignore
import { TelephonyRequestBuilderNavigationMetadata, type TelephonyRequestBuilder } from './telephony/index.js';
// @ts-ignore
import { TransactionsRequestBuilderNavigationMetadata, type TransactionsRequestBuilder } from './transactions/index.js';
// @ts-ignore
import { type UsageRequestBuilder, UsageRequestBuilderNavigationMetadata } from './usage/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata } from './users/index.js';
// @ts-ignore
import { type WalletsRequestBuilder, WalletsRequestBuilderNavigationMetadata } from './wallets/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link LeadpingOpenApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createLeadpingOpenApiClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://api.leadping.ai";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<LeadpingOpenApiClient>(requestAdapter, pathParameters, LeadpingOpenApiClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface LeadpingOpenApiClient extends BaseRequestBuilder<LeadpingOpenApiClient> {
    /**
     * The analytics property
     */
    get analytics(): AnalyticsRequestBuilder;
    /**
     * The automations property
     */
    get automations(): AutomationsRequestBuilder;
    /**
     * The businesses property
     */
    get businesses(): BusinessesRequestBuilder;
    /**
     * The contact property
     */
    get contact(): ContactRequestBuilder;
    /**
     * The conversations property
     */
    get conversations(): ConversationsRequestBuilder;
    /**
     * The dispositions property
     */
    get dispositions(): DispositionsRequestBuilder;
    /**
     * The events property
     */
    get events(): EventsRequestBuilder;
    /**
     * The feedback property
     */
    get feedback(): FeedbackRequestBuilder;
    /**
     * The leads property
     */
    get leads(): LeadsRequestBuilder;
    /**
     * The leadStatuses property
     */
    get leadStatuses(): LeadStatusesRequestBuilder;
    /**
     * The notifications property
     */
    get notifications(): NotificationsRequestBuilder;
    /**
     * The outbound property
     */
    get outbound(): OutboundRequestBuilder;
    /**
     * The paymentMethods property
     */
    get paymentMethods(): PaymentMethodsRequestBuilder;
    /**
     * The phoneCall property
     */
    get phoneCall(): PhoneCallRequestBuilder;
    /**
     * The phoneNumbers property
     */
    get phoneNumbers(): PhoneNumbersRequestBuilder;
    /**
     * The reports property
     */
    get reports(): ReportsRequestBuilder;
    /**
     * The sms property
     */
    get sms(): SmsRequestBuilder;
    /**
     * The sources property
     */
    get sources(): SourcesRequestBuilder;
    /**
     * The suppressions property
     */
    get suppressions(): SuppressionsRequestBuilder;
    /**
     * The tags property
     */
    get tags(): TagsRequestBuilder;
    /**
     * The telephony property
     */
    get telephony(): TelephonyRequestBuilder;
    /**
     * The transactions property
     */
    get transactions(): TransactionsRequestBuilder;
    /**
     * The usage property
     */
    get usage(): UsageRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
    /**
     * The wallets property
     */
    get wallets(): WalletsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LeadpingOpenApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadpingOpenApiClientNavigationMetadata: Record<Exclude<keyof LeadpingOpenApiClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    analytics: {
        navigationMetadata: AnalyticsRequestBuilderNavigationMetadata,
    },
    automations: {
        requestsMetadata: AutomationsRequestBuilderRequestsMetadata,
        navigationMetadata: AutomationsRequestBuilderNavigationMetadata,
    },
    businesses: {
        navigationMetadata: BusinessesRequestBuilderNavigationMetadata,
    },
    contact: {
        requestsMetadata: ContactRequestBuilderRequestsMetadata,
    },
    conversations: {
        navigationMetadata: ConversationsRequestBuilderNavigationMetadata,
    },
    dispositions: {
        requestsMetadata: DispositionsRequestBuilderRequestsMetadata,
        navigationMetadata: DispositionsRequestBuilderNavigationMetadata,
    },
    events: {
        navigationMetadata: EventsRequestBuilderNavigationMetadata,
    },
    feedback: {
        requestsMetadata: FeedbackRequestBuilderRequestsMetadata,
    },
    leads: {
        requestsMetadata: LeadsRequestBuilderRequestsMetadata,
        navigationMetadata: LeadsRequestBuilderNavigationMetadata,
    },
    leadStatuses: {
        requestsMetadata: LeadStatusesRequestBuilderRequestsMetadata,
        navigationMetadata: LeadStatusesRequestBuilderNavigationMetadata,
    },
    notifications: {
        navigationMetadata: NotificationsRequestBuilderNavigationMetadata,
    },
    outbound: {
        navigationMetadata: OutboundRequestBuilderNavigationMetadata,
    },
    paymentMethods: {
        requestsMetadata: PaymentMethodsRequestBuilderRequestsMetadata,
        navigationMetadata: PaymentMethodsRequestBuilderNavigationMetadata,
    },
    phoneCall: {
        navigationMetadata: PhoneCallRequestBuilderNavigationMetadata,
    },
    phoneNumbers: {
        requestsMetadata: PhoneNumbersRequestBuilderRequestsMetadata,
        navigationMetadata: PhoneNumbersRequestBuilderNavigationMetadata,
    },
    reports: {
        navigationMetadata: ReportsRequestBuilderNavigationMetadata,
    },
    sms: {
        navigationMetadata: SmsRequestBuilderNavigationMetadata,
    },
    sources: {
        requestsMetadata: SourcesRequestBuilderRequestsMetadata,
        navigationMetadata: SourcesRequestBuilderNavigationMetadata,
    },
    suppressions: {
        requestsMetadata: SuppressionsRequestBuilderRequestsMetadata,
        navigationMetadata: SuppressionsRequestBuilderNavigationMetadata,
    },
    tags: {
        requestsMetadata: TagsRequestBuilderRequestsMetadata,
        navigationMetadata: TagsRequestBuilderNavigationMetadata,
    },
    telephony: {
        navigationMetadata: TelephonyRequestBuilderNavigationMetadata,
    },
    transactions: {
        navigationMetadata: TransactionsRequestBuilderNavigationMetadata,
    },
    usage: {
        navigationMetadata: UsageRequestBuilderNavigationMetadata,
    },
    users: {
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
    wallets: {
        navigationMetadata: WalletsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
