/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPhoneCallResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeInitiateCallRequest, serializePhoneCallResponse, type InitiateCallRequest, type PhoneCallResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-call/initiate
 */
export interface InitiateRequestBuilder extends BaseRequestBuilder<InitiateRequestBuilder> {
    /**
     * Returns the call details with a 200 status code.
     * @param body Request schema for the Leadping API phone call initiation request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PhoneCallResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: InitiateCallRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PhoneCallResponse | undefined>;
    /**
     * Returns the call details with a 200 status code.
     * @param body Request schema for the Leadping API phone call initiation request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: InitiateCallRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InitiateRequestBuilderUriTemplate = "{+baseurl}/phone-call/initiate";
/**
 * Metadata for all the requests in the request builder.
 */
export const InitiateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InitiateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPhoneCallResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeInitiateCallRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
