/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAutomationPreviewResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAutomationPreviewRequest, serializeAutomationPreviewResponse, type AutomationPreviewRequest, type AutomationPreviewResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /automations/preview
 */
export interface PreviewRequestBuilder extends BaseRequestBuilder<PreviewRequestBuilder> {
    /**
     * Previews automation execution for a sample lead, showing matched steps and messages without creating follow-up events.
     * @param body API DTO containing automation preview data used by Leadping API contracts.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AutomationPreviewResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: AutomationPreviewRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AutomationPreviewResponse | undefined>;
    /**
     * Previews automation execution for a sample lead, showing matched steps and messages without creating follow-up events.
     * @param body API DTO containing automation preview data used by Leadping API contracts.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AutomationPreviewRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PreviewRequestBuilderUriTemplate = "{+baseurl}/automations/preview";
/**
 * Metadata for all the requests in the request builder.
 */
export const PreviewRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PreviewRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAutomationPreviewResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAutomationPreviewRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
