/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAutomationPreviewResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAutomationPreviewRequest, serializeAutomationPreviewResponse, type AutomationPreviewRequest, type AutomationPreviewResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /automations/preview
 */
export interface PreviewRequestBuilder extends BaseRequestBuilder<PreviewRequestBuilder> {
    /**
     * Preview matched automation steps and messages for a sample lead without creating follow-up events, or use validate_only to check the automation configuration.
     * @param body Defines the fields clients can send when working with automation preview.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AutomationPreviewResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: AutomationPreviewRequest, requestConfiguration?: RequestConfiguration<PreviewRequestBuilderPostQueryParameters> | undefined) : Promise<AutomationPreviewResponse | undefined>;
    /**
     * Preview matched automation steps and messages for a sample lead without creating follow-up events, or use validate_only to check the automation configuration.
     * @param body Defines the fields clients can send when working with automation preview.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AutomationPreviewRequest, requestConfiguration?: RequestConfiguration<PreviewRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Preview matched automation steps and messages for a sample lead without creating follow-up events, or use validate_only to check the automation configuration.
 */
export interface PreviewRequestBuilderPostQueryParameters {
    /**
     * When true, validates the automation without evaluating actions or writing an audit event.
     */
    validateOnly?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const PreviewRequestBuilderUriTemplate = "{+baseurl}/automations/preview{?validate_only*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const PreviewRequestBuilderPostQueryParametersMapper: Record<string, string> = {
    "validateOnly": "validate_only",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PreviewRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PreviewRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAutomationPreviewResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAutomationPreviewRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
        queryParametersMapper: PreviewRequestBuilderPostQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
