/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeLeadIntakeRequest, serializeLeadResponse, type LeadIntakeRequest, type LeadResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type DateOnly, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /leads/intake
 */
export interface IntakeRequestBuilder extends BaseRequestBuilder<IntakeRequestBuilder> {
    /**
     * Creates a source-authenticated lead from query parameters, supporting simple form posts, tracking metadata, and follow-up automation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<IntakeRequestBuilderGetQueryParameters> | undefined) : Promise<LeadResponse | undefined>;
    /**
     * Creates a source-authenticated lead from a flat intake payload, capturing contact fields, metadata, and automation-ready lead details.
     * @param body Request payload for lead intake.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     post(body: LeadIntakeRequest, requestConfiguration?: RequestConfiguration<IntakeRequestBuilderPostQueryParameters> | undefined) : Promise<LeadResponse | undefined>;
    /**
     * Creates a source-authenticated lead from query parameters, supporting simple form posts, tracking metadata, and follow-up automation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<IntakeRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Creates a source-authenticated lead from a flat intake payload, capturing contact fields, metadata, and automation-ready lead details.
     * @param body Request payload for lead intake.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LeadIntakeRequest, requestConfiguration?: RequestConfiguration<IntakeRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Creates a source-authenticated lead from query parameters, supporting simple form posts, tracking metadata, and follow-up automation.
 */
export interface IntakeRequestBuilderGetQueryParameters {
    /**
     * The address1 value for this lead intake.
     */
    address1?: string;
    /**
     * The address2 value for this lead intake.
     */
    address2?: string;
    /**
     * The date and time for the birth date value on this lead intake.
     */
    birthDate?: DateOnly;
    /**
     * The city value for this lead intake.
     */
    city?: string;
    /**
     * The date and time for the date of birth value on this lead intake.
     */
    dateOfBirth?: DateOnly;
    /**
     * The direct post price value for this lead intake.
     */
    directPostPrice?: number;
    /**
     * The email address associated with this lead intake.
     */
    email?: string;
    /**
     * The external ID associated with this lead intake.
     */
    externalId?: string;
    /**
     * The first name value for this lead intake.
     */
    firstName?: string;
    /**
     * The gender value for this lead intake.
     */
    gender?: string;
    /**
     * The landing page value for this lead intake.
     */
    landingPage?: string;
    /**
     * The date and time for the last name value on this lead intake.
     */
    lastName?: string;
    /**
     * The phone number associated with this lead intake.
     */
    phone?: string;
    /**
     * The phone type classification for this lead intake.
     */
    phoneType?: string;
    /**
     * The postal code value for this lead intake.
     */
    postalCode?: string;
    /**
     * The monetary price for this lead intake.
     */
    price?: number;
    /**
     * The product value for this lead intake.
     */
    product?: string;
    /**
     * The referrer value for this lead intake.
     */
    referrer?: string;
    /**
     * The seller lead ID associated with this lead intake.
     */
    sellerLeadId?: string;
    /**
     * The seller lead identifier value for this lead intake.
     */
    sellerLeadIdentifier?: string;
    /**
     * The Leadping source key supplied as a query string parameter.
     */
    sourceKey?: string;
    /**
     * The source metadata key-value data carried with this lead intake; values must be safe to expose in API responses.
     */
    sourceMetadata?: string;
    /**
     * The current state for this lead intake.
     */
    state?: string;
    /**
     * The sub ID associated with this lead intake.
     */
    subId?: string;
    /**
     * Existing business tag ids to assign as part of intake.
     */
    tagIds?: string[];
    /**
     * Business tag names to assign as part of intake.
     */
    tagNames?: string[];
    /**
     * The URL associated with this lead intake.
     */
    trustedFormUrl?: string;
    /**
     * The utm campaign value for this lead intake.
     */
    utmCampaign?: string;
    /**
     * The utm content value for this lead intake.
     */
    utmContent?: string;
    /**
     * The utm medium value for this lead intake.
     */
    utmMedium?: string;
    /**
     * The utm source value for this lead intake.
     */
    utmSource?: string;
    /**
     * The utm term value for this lead intake.
     */
    utmTerm?: string;
    /**
     * The vertical value for this lead intake.
     */
    vertical?: string;
    /**
     * The zip value for this lead intake.
     */
    zip?: string;
}
/**
 * Creates a source-authenticated lead from a flat intake payload, capturing contact fields, metadata, and automation-ready lead details.
 */
export interface IntakeRequestBuilderPostQueryParameters {
    /**
     * The Leadping source key supplied as a query string parameter.
     */
    sourceKey?: string;
}
/**
 * Uri template for the request builder.
 */
export const IntakeRequestBuilderUriTemplate = "{+baseurl}/leads/intake{?Address1*,Address2*,BirthDate*,City*,DateOfBirth*,DirectPostPrice*,Email*,ExternalId*,FirstName*,Gender*,LandingPage*,LastName*,Phone*,PhoneType*,PostalCode*,Price*,Product*,Referrer*,SellerLeadId*,SellerLeadIdentifier*,SourceMetadata*,State*,SubId*,TagIds*,TagNames*,TrustedFormUrl*,UtmCampaign*,UtmContent*,UtmMedium*,UtmSource*,UtmTerm*,Vertical*,Zip*,sourceKey*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const IntakeRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "address1": "Address1",
    "address2": "Address2",
    "birthDate": "BirthDate",
    "city": "City",
    "dateOfBirth": "DateOfBirth",
    "directPostPrice": "DirectPostPrice",
    "email": "Email",
    "externalId": "ExternalId",
    "firstName": "FirstName",
    "gender": "Gender",
    "landingPage": "LandingPage",
    "lastName": "LastName",
    "phone": "Phone",
    "phoneType": "PhoneType",
    "postalCode": "PostalCode",
    "price": "Price",
    "product": "Product",
    "referrer": "Referrer",
    "sellerLeadId": "SellerLeadId",
    "sellerLeadIdentifier": "SellerLeadIdentifier",
    "sourceMetadata": "SourceMetadata",
    "state": "State",
    "subId": "SubId",
    "tagIds": "TagIds",
    "tagNames": "TagNames",
    "trustedFormUrl": "TrustedFormUrl",
    "utmCampaign": "UtmCampaign",
    "utmContent": "UtmContent",
    "utmMedium": "UtmMedium",
    "utmSource": "UtmSource",
    "utmTerm": "UtmTerm",
    "vertical": "Vertical",
    "zip": "Zip",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const IntakeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: IntakeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLeadResponseFromDiscriminatorValue,
        queryParametersMapper: IntakeRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: IntakeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLeadResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadIntakeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
