/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfEventTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfEventTableRow, serializeRequestDataOptions, type PagedResultOfEventTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/organizations/{organizationId}
 */
export interface WithOrganizationItemRequestBuilder extends BaseRequestBuilder<WithOrganizationItemRequestBuilder> {
    /**
     * Lists event records for an organization with paging and filters so admins can review lead communication and automation events.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfEventTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<WithOrganizationItemRequestBuilderPostQueryParameters> | undefined) : Promise<PagedResultOfEventTableRow | undefined>;
    /**
     * Lists event records for an organization with paging and filters so admins can review lead communication and automation events.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<WithOrganizationItemRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lists event records for an organization with paging and filters so admins can review lead communication and automation events.
 */
export interface WithOrganizationItemRequestBuilderPostQueryParameters {
    /**
     * Optional exclusive end timestamp for event occurrence.
     */
    endAt?: Date;
    /**
     * Optional inclusive start timestamp for event occurrence.
     */
    startAt?: Date;
}
/**
 * Uri template for the request builder.
 */
export const WithOrganizationItemRequestBuilderUriTemplate = "{+baseurl}/events/organizations/{organizationId}{?endAt*,startAt*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithOrganizationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithOrganizationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfEventTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
