/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithPhoneNumberItemRequestBuilder, WithPhoneNumberItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/calls/phone
 */
export interface PhoneRequestBuilder extends BaseRequestBuilder<PhoneRequestBuilder> {
    /**
     * Gets an item from the leadping.events.calls.phone.item collection
     * @param phoneNumber The phone number to search for.
     * @returns {WithPhoneNumberItemRequestBuilder}
     */
     byPhoneNumber(phoneNumber: string) : WithPhoneNumberItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PhoneRequestBuilderUriTemplate = "{+baseurl}/events/calls/phone";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PhoneRequestBuilderNavigationMetadata: Record<Exclude<keyof PhoneRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPhoneNumber: {
        requestsMetadata: WithPhoneNumberItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["phoneNumber"],
    },
};
/* tslint:enable */
/* eslint-enable */
