/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfFeedbackResponseFromDiscriminatorValue, type PagedResultOfFeedbackResponse } from '../../models/index.js';
// @ts-ignore
import { AdminItemRequestBuilderRequestsMetadata, type AdminItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /feedback/admin
 */
export interface AdminRequestBuilder extends BaseRequestBuilder<AdminRequestBuilder> {
    /**
     * Gets an item from the leadping.feedback.admin.item collection
     * @param id Unique identifier of the item
     * @returns {AdminItemRequestBuilder}
     */
     byId(id: string) : AdminItemRequestBuilder;
    /**
     * Lists submitted feedback for admin triage with query filters, paging, status, and category review fields.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfFeedbackResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<AdminRequestBuilderGetQueryParameters> | undefined) : Promise<PagedResultOfFeedbackResponse | undefined>;
    /**
     * Lists submitted feedback for admin triage with query filters, paging, status, and category review fields.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AdminRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lists submitted feedback for admin triage with query filters, paging, status, and category review fields.
 */
export interface AdminRequestBuilderGetQueryParameters {
    /**
     * Product area or app section connected to this feedback admin query request.
     */
    area?: string;
    /**
     * Business ID used to filter feedback items for admin review.
     */
    businessId?: string;
    /**
     * Pagination token used to request the next page of Leadping API results.
     */
    continuationToken?: string;
    /**
     * End of the created-at date range filter for Leadping API results.
     */
    createdEnd?: Date;
    /**
     * Start of the created-at date range filter for Leadping API results.
     */
    createdStart?: Date;
    /**
     * Maximum number of results requested for this Leadping API page.
     */
    pageSize?: number;
    /**
     * Search text used to filter Leadping API results.
     */
    search?: string;
    /**
     * Current lifecycle status for this feedback admin query request in the Leadping API.
     */
    status?: string;
    /**
     * Type classification used to route and interpret this feedback admin query request in the Leadping API.
     */
    type?: string;
}
/**
 * Uri template for the request builder.
 */
export const AdminRequestBuilderUriTemplate = "{+baseurl}/feedback/admin{?Area*,BusinessId*,ContinuationToken*,CreatedEnd*,CreatedStart*,PageSize*,Search*,Status*,Type*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AdminRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "area": "Area",
    "businessId": "BusinessId",
    "continuationToken": "ContinuationToken",
    "createdEnd": "CreatedEnd",
    "createdStart": "CreatedStart",
    "pageSize": "PageSize",
    "search": "Search",
    "status": "Status",
    "type": "Type",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AdminItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AdminRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AdminRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfFeedbackResponseFromDiscriminatorValue,
        queryParametersMapper: AdminRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
