/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, serializePushInstallationRequest, type ProblemDetails, type PushInstallationRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications/push/installations/current
 */
export interface CurrentRequestBuilder extends BaseRequestBuilder<CurrentRequestBuilder> {
    /**
     * Register or refresh the current user's mobile push installation.
     * @param body Describes a mobile push installation. Identity and Azure tags are derived by the API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<boolean>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     put(body: PushInstallationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<boolean | undefined>;
    /**
     * Register or refresh the current user's mobile push installation.
     * @param body Describes a mobile push installation. Identity and Azure tags are derived by the API.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: PushInstallationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CurrentRequestBuilderUriTemplate = "{+baseurl}/notifications/push/installations/current";
/**
 * Metadata for all the requests in the request builder.
 */
export const CurrentRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: CurrentRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "boolean",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePushInstallationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
