/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithConversationItemRequestBuilder, WithConversationItemRequestBuilderNavigationMetadata, WithConversationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/conversations
 */
export interface ConversationsRequestBuilder extends BaseRequestBuilder<ConversationsRequestBuilder> {
    /**
     * Gets an item from the leadping.events.conversations.item collection
     * @param conversationId The ID of the conversation.
     * @returns {WithConversationItemRequestBuilder}
     */
     byConversationId(conversationId: string) : WithConversationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConversationsRequestBuilderUriTemplate = "{+baseurl}/events/conversations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationsRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byConversationId: {
        requestsMetadata: WithConversationItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithConversationItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["conversationId"],
    },
};
/* tslint:enable */
/* eslint-enable */
