/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAutomationResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeAutomationRequest, serializeAutomationResponse, type AutomationRequest, type AutomationResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { RunRequestBuilderRequestsMetadata, type RunRequestBuilder } from './run/index.js';
// @ts-ignore
import { RunsRequestBuilderNavigationMetadata, RunsRequestBuilderRequestsMetadata, type RunsRequestBuilder } from './runs/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /automations/{id}
 */
export interface AutomationsItemRequestBuilder extends BaseRequestBuilder<AutomationsItemRequestBuilder> {
    /**
     * The run property
     */
    get run(): RunRequestBuilder;
    /**
     * The runs property
     */
    get runs(): RunsRequestBuilder;
    /**
     * Deletes an automation for the current organization so it no longer schedules follow-up or routing work for captured leads.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<boolean>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<boolean | undefined>;
    /**
     * Returns one automation for the current organization, including trigger criteria, message steps, routing settings, and enabled state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AutomationResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AutomationResponse | undefined>;
    /**
     * Updates an automation for current-organization leads, changing triggers, message steps, routing, or active follow-up settings.
     * @param body Defines the fields clients can send when working with automation configuration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AutomationResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     put(body: AutomationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AutomationResponse | undefined>;
    /**
     * Deletes an automation for the current organization so it no longer schedules follow-up or routing work for captured leads.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Returns one automation for the current organization, including trigger criteria, message steps, routing settings, and enabled state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates an automation for current-organization leads, changing triggers, message steps, routing, or active follow-up settings.
     * @param body Defines the fields clients can send when working with automation configuration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: AutomationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AutomationsItemRequestBuilderUriTemplate = "{+baseurl}/automations/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AutomationsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof AutomationsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    run: {
        requestsMetadata: RunRequestBuilderRequestsMetadata,
    },
    runs: {
        requestsMetadata: RunsRequestBuilderRequestsMetadata,
        navigationMetadata: RunsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AutomationsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: AutomationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "boolean",
    },
    get: {
        uriTemplate: AutomationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAutomationResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: AutomationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAutomationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAutomationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
