/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSuppressionCheckResultFromDiscriminatorValue, serializeSuppressionCheckResult, serializeSuppressionEntryRequest, type ProblemDetails, type SuppressionCheckResult, type SuppressionEntryRequest } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /suppressions/check
 */
export interface CheckRequestBuilder extends BaseRequestBuilder<CheckRequestBuilder> {
    /**
     * Returns the suppression check result.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuppressionCheckResult>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuppressionCheckResult | undefined>;
    /**
     * Returns the suppression check result.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckRequestBuilderUriTemplate = "{+baseurl}/suppressions/check";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuppressionCheckResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSuppressionEntryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
