/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSourceResponseFromDiscriminatorValue, serializeSourceRequest, serializeSourceResponse, type ProblemDetails, type SourceRequest, type SourceResponse } from '../models/index.js';
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { SourcesItemRequestBuilderNavigationMetadata, SourcesItemRequestBuilderRequestsMetadata, type SourcesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sources
 */
export interface SourcesRequestBuilder extends BaseRequestBuilder<SourcesRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * Gets an item from the leadping.sources.item collection
     * @param id The ID of the source to update.
     * @returns {SourcesItemRequestBuilder}
     */
     byId(id: string) : SourcesItemRequestBuilder;
    /**
     * Creates a lead source for the current business, storing intake credentials and routing context for captured external leads.
     * @param body Request schema for the Leadping API lead source request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SourceResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: SourceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SourceResponse | undefined>;
    /**
     * Creates a lead source for the current business, storing intake credentials and routing context for captured external leads.
     * @param body Request schema for the Leadping API lead source request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SourceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SourcesRequestBuilderUriTemplate = "{+baseurl}/sources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof SourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SourcesItemRequestBuilderRequestsMetadata,
        navigationMetadata: SourcesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSourceResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSourceRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
