/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { SummaryRequestBuilderNavigationMetadata, type SummaryRequestBuilder } from './summary/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /usage
 */
export interface UsageRequestBuilder extends BaseRequestBuilder<UsageRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The summary property
     */
    get summary(): SummaryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UsageRequestBuilderUriTemplate = "{+baseurl}/usage";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsageRequestBuilderNavigationMetadata: Record<Exclude<keyof UsageRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    summary: {
        navigationMetadata: SummaryRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
