/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadStatusChangeResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type LeadStatusChangeResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { ExportRequestBuilderRequestsMetadata, type ExportRequestBuilder } from './exportEscaped/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /leads/{-id}/status-history
 */
export interface StatusHistoryRequestBuilder extends BaseRequestBuilder<StatusHistoryRequestBuilder> {
    /**
     * The export property
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * Lists lead status change outcome history for one lead, including prior outcomes, notes, follow-up context, timestamps, and actor details used for audit review.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusChangeResponse[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusChangeResponse[] | undefined>;
    /**
     * Lists lead status change outcome history for one lead, including prior outcomes, notes, follow-up context, timestamps, and actor details used for audit review.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatusHistoryRequestBuilderUriTemplate = "{+baseurl}/leads/{%2Did}/status-history";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StatusHistoryRequestBuilderNavigationMetadata: Record<Exclude<keyof StatusHistoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    exportEscaped: {
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StatusHistoryRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatusHistoryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLeadStatusChangeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
