/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithEventItemRequestBuilder, WithEventItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/detail
 */
export interface DetailRequestBuilder extends BaseRequestBuilder<DetailRequestBuilder> {
    /**
     * Gets an item from the leadping.events.detail.item collection
     * @param eventId The ID of the event.
     * @returns {WithEventItemRequestBuilder}
     */
     byEventId(eventId: string) : WithEventItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DetailRequestBuilderUriTemplate = "{+baseurl}/events/detail";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DetailRequestBuilderNavigationMetadata: Record<Exclude<keyof DetailRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byEventId: {
        requestsMetadata: WithEventItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["eventId"],
    },
};
/* tslint:enable */
/* eslint-enable */
