/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications/push/installations/{installationId}
 */
export interface WithInstallationItemRequestBuilder extends BaseRequestBuilder<WithInstallationItemRequestBuilder> {
    /**
     * Removes a mobile push installation from the authenticated user's account so Leadping no longer sends notifications to that device.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<boolean>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<boolean | undefined>;
    /**
     * Removes a mobile push installation from the authenticated user's account so Leadping no longer sends notifications to that device.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithInstallationItemRequestBuilderUriTemplate = "{+baseurl}/notifications/push/installations/{installationId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithInstallationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithInstallationItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "boolean",
    },
};
/* tslint:enable */
/* eslint-enable */
