/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { InitiateRequestBuilderRequestsMetadata, type InitiateRequestBuilder } from './initiate/index.js';
// @ts-ignore
import { type WithCallItemRequestBuilder, WithCallItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-call
 */
export interface PhoneCallRequestBuilder extends BaseRequestBuilder<PhoneCallRequestBuilder> {
    /**
     * The initiate property
     */
    get initiate(): InitiateRequestBuilder;
    /**
     * Gets an item from the leadping.phoneCall.item collection
     * @param callId The unique identifier of the call to end.
     * @returns {WithCallItemRequestBuilder}
     */
     byCallId(callId: string) : WithCallItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PhoneCallRequestBuilderUriTemplate = "{+baseurl}/phone-call";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PhoneCallRequestBuilderNavigationMetadata: Record<Exclude<keyof PhoneCallRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCallId: {
        navigationMetadata: WithCallItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["callId"],
    },
    initiate: {
        requestsMetadata: InitiateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
