/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSuppressionEntryResponseFromDiscriminatorValue, serializeSuppressionEntryRequest, serializeSuppressionEntryResponse, type ProblemDetails, type SuppressionEntryRequest, type SuppressionEntryResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /suppressions/release
 */
export interface ReleaseRequestBuilder extends BaseRequestBuilder<ReleaseRequestBuilder> {
    /**
     * Releases an active Leadping suppression entry so a recipient can be contacted again, returning the updated suppression record when available.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuppressionEntryResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuppressionEntryResponse | undefined>;
    /**
     * Releases an active Leadping suppression entry so a recipient can be contacted again, returning the updated suppression record when available.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ReleaseRequestBuilderUriTemplate = "{+baseurl}/suppressions/release";
/**
 * Metadata for all the requests in the request builder.
 */
export const ReleaseRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ReleaseRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuppressionEntryResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSuppressionEntryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
