/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessUserResponseFromDiscriminatorValue, createBusinessUserTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeBusinessUserRequest, serializeBusinessUserResponse, type BusinessUserRequest, type BusinessUserResponse, type BusinessUserTableRow, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses/me/users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Gets an item from the leadping.businesses.me.users.item collection
     * @param userId The ID of the user whose current-business role is changing.
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
    /**
     * Lists users assigned to the current business, including roles and membership details for access management.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BusinessUserTableRow[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BusinessUserTableRow[] | undefined>;
    /**
     * Adds an existing user to the current business with the requested role for shared lead communication and account access.
     * @param body Request payload for business user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BusinessUserResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     post(body: BusinessUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BusinessUserResponse | undefined>;
    /**
     * Lists users assigned to the current business, including roles and membership details for access management.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Adds an existing user to the current business with the requested role for shared lead communication and account access.
     * @param body Request payload for business user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BusinessUserRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/businesses/me/users";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UsersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBusinessUserTableRowFromDiscriminatorValue,
    },
    post: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBusinessUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBusinessUserRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
