/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { TransactionsItemRequestBuilderRequestsMetadata, type TransactionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /transactions
 */
export interface TransactionsRequestBuilder extends BaseRequestBuilder<TransactionsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * Gets an item from the leadping.transactions.item collection
     * @param id The ID of the transaction to retrieve.
     * @returns {TransactionsItemRequestBuilder}
     */
     byId(id: string) : TransactionsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TransactionsRequestBuilderUriTemplate = "{+baseurl}/transactions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TransactionsRequestBuilderNavigationMetadata: Record<Exclude<keyof TransactionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TransactionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
