/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfCallEventTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfCallEventTableRow, serializeRequestDataOptions, type PagedResultOfCallEventTableRow, type ProblemDetails, type RequestDataOptions } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/calls/phone/{phoneNumber}
 */
export interface WithPhoneNumberItemRequestBuilder extends BaseRequestBuilder<WithPhoneNumberItemRequestBuilder> {
    /**
     * Lists call events for one phone number with paging, helping users review volume, outcomes, and communication history.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfCallEventTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfCallEventTableRow | undefined>;
    /**
     * Lists call events for one phone number with paging, helping users review volume, outcomes, and communication history.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPhoneNumberItemRequestBuilderUriTemplate = "{+baseurl}/events/calls/phone/{phoneNumber}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPhoneNumberItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithPhoneNumberItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfCallEventTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
