/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadStatusResponseFromDiscriminatorValue, serializeLeadStatusRequest, serializeLeadStatusResponse, type LeadStatusRequest, type LeadStatusResponse } from '../models/index.js';
// @ts-ignore
import { LeadStatusesItemRequestBuilderRequestsMetadata, type LeadStatusesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /lead-statuses
 */
export interface LeadStatusesRequestBuilder extends BaseRequestBuilder<LeadStatusesRequestBuilder> {
    /**
     * Gets an item from the leadping.leadStatuses.item collection
     * @param id Unique identifier of the item
     * @returns {LeadStatusesItemRequestBuilder}
     */
     byId(id: string) : LeadStatusesItemRequestBuilder;
    /**
     * Get all
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusResponse[] | undefined>;
    /**
     * Create
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusResponse>}
     */
     post(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusResponse | undefined>;
    /**
     * Get all
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LeadStatusesRequestBuilderUriTemplate = "{+baseurl}/lead-statuses";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadStatusesRequestBuilderNavigationMetadata: Record<Exclude<keyof LeadStatusesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LeadStatusesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LeadStatusesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LeadStatusesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLeadStatusResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: LeadStatusesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createLeadStatusResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadStatusRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
