/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadStatusResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeLeadStatusRequest, serializeLeadStatusResponse, type LeadStatusRequest, type LeadStatusResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { LeadStatusesItemRequestBuilderRequestsMetadata, type LeadStatusesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /lead-statuses
 */
export interface LeadStatusesRequestBuilder extends BaseRequestBuilder<LeadStatusesRequestBuilder> {
    /**
     * Gets an item from the leadping.leadStatuses.item collection
     * @param id The unique identifier of the lead status to update.
     * @returns {LeadStatusesItemRequestBuilder}
     */
     byId(id: string) : LeadStatusesItemRequestBuilder;
    /**
     * Lists the current organization's active lead statuses for organizing and tracking leads through the sales workflow.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusResponse[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusResponse[] | undefined>;
    /**
     * Creates a reusable lead status for the current organization to categorize, organize, and track leads consistently throughout its sales and follow-up workflow.
     * @param body Defines the editable values used to create or update a lead status.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusResponse | undefined>;
    /**
     * Lists the current organization's active lead statuses for organizing and tracking leads through the sales workflow.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Creates a reusable lead status for the current organization to categorize, organize, and track leads consistently throughout its sales and follow-up workflow.
     * @param body Defines the editable values used to create or update a lead status.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LeadStatusesRequestBuilderUriTemplate = "{+baseurl}/lead-statuses";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadStatusesRequestBuilderNavigationMetadata: Record<Exclude<keyof LeadStatusesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LeadStatusesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LeadStatusesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LeadStatusesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLeadStatusResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: LeadStatusesRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLeadStatusResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadStatusRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
