/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBlogArticleResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type BlogArticleResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /blog/{slug}
 */
export interface WithSlugItemRequestBuilder extends BaseRequestBuilder<WithSlugItemRequestBuilder> {
    /**
     * Returns the public article identified by its URL slug, or a not-found response when no published article matches.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BlogArticleResponse>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BlogArticleResponse | undefined>;
    /**
     * Returns the public article identified by its URL slug, or a not-found response when no published article matches.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithSlugItemRequestBuilderUriTemplate = "{+baseurl}/blog/{slug}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSlugItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithSlugItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBlogArticleResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
