/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PdfAccessRequestBuilderRequestsMetadata, type PdfAccessRequestBuilder } from './pdfAccess/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payment-methods/invoices/{invoiceId}
 */
export interface WithInvoiceItemRequestBuilder extends BaseRequestBuilder<WithInvoiceItemRequestBuilder> {
    /**
     * The pdfAccess property
     */
    get pdfAccess(): PdfAccessRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithInvoiceItemRequestBuilderUriTemplate = "{+baseurl}/payment-methods/invoices/{invoiceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithInvoiceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithInvoiceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    pdfAccess: {
        requestsMetadata: PdfAccessRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
