/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LeadRequestBuilderNavigationMetadata, type LeadRequestBuilder } from './lead/index.js';
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /conversations
 */
export interface ConversationsRequestBuilder extends BaseRequestBuilder<ConversationsRequestBuilder> {
    /**
     * The lead property
     */
    get lead(): LeadRequestBuilder;
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConversationsRequestBuilderUriTemplate = "{+baseurl}/conversations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationsRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    lead: {
        navigationMetadata: LeadRequestBuilderNavigationMetadata,
    },
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
