/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPhoneNumberStatusResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type PhoneNumberStatusResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type DateOnly, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/{phoneNumber-id}/status
 */
export interface StatusRequestBuilder extends BaseRequestBuilder<StatusRequestBuilder> {
    /**
     * Returns provider and Leadping status for a phone number, including messaging warmup, assignments, and verification state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PhoneNumberStatusResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<StatusRequestBuilderGetQueryParameters> | undefined) : Promise<PhoneNumberStatusResponse | undefined>;
    /**
     * Returns provider and Leadping status for a phone number, including messaging warmup, assignments, and verification state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StatusRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns provider and Leadping status for a phone number, including messaging warmup, assignments, and verification state.
 */
export interface StatusRequestBuilderGetQueryParameters {
    /**
     * The end date.
     */
    endDate?: DateOnly;
    /**
     * The start date.
     */
    startDate?: DateOnly;
    /**
     * The window days.
     */
    windowDays?: number;
}
/**
 * Uri template for the request builder.
 */
export const StatusRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/{phoneNumber%2Did}/status{?endDate*,startDate*,windowDays*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatusRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatusRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPhoneNumberStatusResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
