/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfTransactionTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfTransactionTableRow, serializeRequestDataOptions, type PagedResultOfTransactionTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /transactions/all/my
 */
export interface MyRequestBuilder extends BaseRequestBuilder<MyRequestBuilder> {
    /**
     * Lists current-user transactions with paging, sorting, and filters for wallet events, billing history, and reconciliation.
     * @param body Defines cursor pagination, sorting, search, exact-match filters, and range filters for a structured API query.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfTransactionTableRow>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : Promise<PagedResultOfTransactionTableRow | undefined>;
    /**
     * Lists current-user transactions with paging, sorting, and filters for wallet events, billing history, and reconciliation.
     * @param body Defines cursor pagination, sorting, search, exact-match filters, and range filters for a structured API query.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lists current-user transactions with paging, sorting, and filters for wallet events, billing history, and reconciliation.
 */
export interface MyRequestBuilderPostQueryParameters {
    /**
     * Optional exclusive end timestamp for transaction creation.
     */
    endAt?: Date;
    /**
     * Optional inclusive start timestamp for transaction creation.
     */
    startAt?: Date;
}
/**
 * Uri template for the request builder.
 */
export const MyRequestBuilderUriTemplate = "{+baseurl}/transactions/all/my{?endAt*,startAt*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfTransactionTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
