/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfConversationResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfConversationResponse, serializeRequestDataOptions, type PagedResultOfConversationResponse, type ProblemDetails, type RequestDataOptions } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /conversations/my
 */
export interface MyRequestBuilder extends BaseRequestBuilder<MyRequestBuilder> {
    /**
     * Lists the current user's lead conversations with paging and sorting for inbox views, recent follow-up, and communication history.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfConversationResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : Promise<PagedResultOfConversationResponse | undefined>;
    /**
     * Lists the current user's lead conversations with paging and sorting for inbox views, recent follow-up, and communication history.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lists the current user's lead conversations with paging and sorting for inbox views, recent follow-up, and communication history.
 */
export interface MyRequestBuilderPostQueryParameters {
    archiveFilter?: string;
}
/**
 * Uri template for the request builder.
 */
export const MyRequestBuilderUriTemplate = "{+baseurl}/conversations/my{?archiveFilter*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MyRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfConversationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
