/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CurrentRequestBuilderRequestsMetadata, type CurrentRequestBuilder } from './current/index.js';
// @ts-ignore
import { type WithInstallationItemRequestBuilder, WithInstallationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications/push/installations
 */
export interface InstallationsRequestBuilder extends BaseRequestBuilder<InstallationsRequestBuilder> {
    /**
     * The current property
     */
    get current(): CurrentRequestBuilder;
    /**
     * Gets an item from the leadping.notifications.push.installations.item collection
     * @param installationId Unique identifier of the item
     * @returns {WithInstallationItemRequestBuilder}
     */
     byInstallationId(installationId: string) : WithInstallationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InstallationsRequestBuilderUriTemplate = "{+baseurl}/notifications/push/installations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InstallationsRequestBuilderNavigationMetadata: Record<Exclude<keyof InstallationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byInstallationId: {
        requestsMetadata: WithInstallationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["installationId"],
    },
    current: {
        requestsMetadata: CurrentRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
