/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDispositionResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeDispositionRequest, serializeDispositionResponse, type DispositionRequest, type DispositionResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { DispositionsItemRequestBuilderRequestsMetadata, type DispositionsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { LeadRequestBuilderNavigationMetadata, type LeadRequestBuilder } from './lead/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /dispositions
 */
export interface DispositionsRequestBuilder extends BaseRequestBuilder<DispositionsRequestBuilder> {
    /**
     * The lead property
     */
    get lead(): LeadRequestBuilder;
    /**
     * Gets an item from the leadping.dispositions.item collection
     * @param id The ID of the disposition.
     * @returns {DispositionsItemRequestBuilder}
     */
     byId(id: string) : DispositionsItemRequestBuilder;
    /**
     * Sets a lead's current structured outcome while recording the disposition change in history for audit, automation, and reporting.
     * @param body Request model for creating or updating a disposition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DispositionResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     post(body: DispositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DispositionResponse | undefined>;
    /**
     * Sets a lead's current structured outcome while recording the disposition change in history for audit, automation, and reporting.
     * @param body Request model for creating or updating a disposition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DispositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DispositionsRequestBuilderUriTemplate = "{+baseurl}/dispositions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DispositionsRequestBuilderNavigationMetadata: Record<Exclude<keyof DispositionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: DispositionsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    lead: {
        navigationMetadata: LeadRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DispositionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DispositionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDispositionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDispositionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
