/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithConversationItemRequestBuilder, WithConversationItemRequestBuilderNavigationMetadata, WithConversationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/outgoing/conversation
 */
export interface ConversationRequestBuilder extends BaseRequestBuilder<ConversationRequestBuilder> {
    /**
     * Gets an item from the leadping.phoneNumbers.outgoing.conversation.item collection
     * @param conversationId The conversation identifier.
     * @returns {WithConversationItemRequestBuilder}
     */
     byConversationId(conversationId: string) : WithConversationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConversationRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/outgoing/conversation";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byConversationId: {
        requestsMetadata: WithConversationItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithConversationItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["conversationId"],
    },
};
/* tslint:enable */
/* eslint-enable */
