/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPhoneCallResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type PhoneCallResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-call/{callId}/hangup
 */
export interface HangupRequestBuilder extends BaseRequestBuilder<HangupRequestBuilder> {
    /**
     * Ends an active Leadping phone call by call ID and returns the updated call record, including status and provider routing details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PhoneCallResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PhoneCallResponse | undefined>;
    /**
     * Ends an active Leadping phone call by call ID and returns the updated call record, including status and provider routing details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HangupRequestBuilderUriTemplate = "{+baseurl}/phone-call/{callId}/hangup";
/**
 * Metadata for all the requests in the request builder.
 */
export const HangupRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: HangupRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPhoneCallResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
