/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBlogArticleResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type BlogArticleResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { type WithSlugItemRequestBuilder, WithSlugItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /blog
 */
export interface BlogRequestBuilder extends BaseRequestBuilder<BlogRequestBuilder> {
    /**
     * Gets an item from the leadping.blog.item collection
     * @param slug The public URL slug of the published article.
     * @returns {WithSlugItemRequestBuilder}
     */
     bySlug(slug: string) : WithSlugItemRequestBuilder;
    /**
     * Returns the Leadping blog articles currently available to public readers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BlogArticleResponse[]>}
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BlogArticleResponse[] | undefined>;
    /**
     * Returns the Leadping blog articles currently available to public readers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BlogRequestBuilderUriTemplate = "{+baseurl}/blog";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BlogRequestBuilderNavigationMetadata: Record<Exclude<keyof BlogRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySlug: {
        requestsMetadata: WithSlugItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["slug"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BlogRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BlogRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBlogArticleResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
