/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeLeadRequest, serializeLeadResponse, type LeadRequest, type LeadResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { IntakeRequestBuilderRequestsMetadata, type IntakeRequestBuilder } from './intake/index.js';
// @ts-ignore
import { LeadsItemRequestBuilderNavigationMetadata, LeadsItemRequestBuilderRequestsMetadata, type LeadsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /leads
 */
export interface LeadsRequestBuilder extends BaseRequestBuilder<LeadsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The intake property
     */
    get intake(): IntakeRequestBuilder;
    /**
     * Gets an item from the leadping.leads.item collection
     * @param id The ID of the lead to retrieve.
     * @returns {LeadsItemRequestBuilder}
     */
     byId(id: string) : LeadsItemRequestBuilder;
    /**
     * Creates a source-authenticated lead captured outside Leadping, starting follow-up, routing, and automation from structured lead data.
     * @param body Request payload for lead.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     post(body: LeadRequest, requestConfiguration?: RequestConfiguration<LeadsRequestBuilderPostQueryParameters> | undefined) : Promise<LeadResponse | undefined>;
    /**
     * Creates a source-authenticated lead captured outside Leadping, starting follow-up, routing, and automation from structured lead data.
     * @param body Request payload for lead.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LeadRequest, requestConfiguration?: RequestConfiguration<LeadsRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Creates a source-authenticated lead captured outside Leadping, starting follow-up, routing, and automation from structured lead data.
 */
export interface LeadsRequestBuilderPostQueryParameters {
    /**
     * The Leadping source key supplied as a query string parameter.
     */
    sourceKey?: string;
}
/**
 * Uri template for the request builder.
 */
export const LeadsRequestBuilderUriTemplate = "{+baseurl}/leads{?sourceKey*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadsRequestBuilderNavigationMetadata: Record<Exclude<keyof LeadsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LeadsItemRequestBuilderRequestsMetadata,
        navigationMetadata: LeadsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    intake: {
        requestsMetadata: IntakeRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LeadsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LeadsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLeadResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
