/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDispositionResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type DispositionResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { ExportRequestBuilderRequestsMetadata, type ExportRequestBuilder } from './exportEscaped/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /dispositions/lead/{leadId}
 */
export interface WithLeadItemRequestBuilder extends BaseRequestBuilder<WithLeadItemRequestBuilder> {
    /**
     * The export property
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * Lists disposition outcome history for one lead, including prior outcomes, notes, follow-up context, timestamps, and actor details used for audit review.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DispositionResponse[]>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DispositionResponse[] | undefined>;
    /**
     * Lists disposition outcome history for one lead, including prior outcomes, notes, follow-up context, timestamps, and actor details used for audit review.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithLeadItemRequestBuilderUriTemplate = "{+baseurl}/dispositions/lead/{leadId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithLeadItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithLeadItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    exportEscaped: {
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLeadItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithLeadItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDispositionResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
