/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RotateRequestBuilderRequestsMetadata, type RotateRequestBuilder } from './rotate/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sources/{id}/credentials
 */
export interface CredentialsRequestBuilder extends BaseRequestBuilder<CredentialsRequestBuilder> {
    /**
     * The rotate property
     */
    get rotate(): RotateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CredentialsRequestBuilderUriTemplate = "{+baseurl}/sources/{id}/credentials";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CredentialsRequestBuilderNavigationMetadata: Record<Exclude<keyof CredentialsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    rotate: {
        requestsMetadata: RotateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
