/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AcceptRequestBuilderRequestsMetadata, type AcceptRequestBuilder } from './accept/index.js';
// @ts-ignore
import { TokenRequestBuilderNavigationMetadata, type TokenRequestBuilder } from './token/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses/invitations
 */
export interface InvitationsRequestBuilder extends BaseRequestBuilder<InvitationsRequestBuilder> {
    /**
     * The accept property
     */
    get accept(): AcceptRequestBuilder;
    /**
     * The token property
     */
    get token(): TokenRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const InvitationsRequestBuilderUriTemplate = "{+baseurl}/businesses/invitations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InvitationsRequestBuilderNavigationMetadata: Record<Exclude<keyof InvitationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accept: {
        requestsMetadata: AcceptRequestBuilderRequestsMetadata,
    },
    token: {
        navigationMetadata: TokenRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
