/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOrganizationMemberResponseFromDiscriminatorValue, createOrganizationMemberTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeOrganizationMemberRequest, serializeOrganizationMemberResponse, type OrganizationMemberRequest, type OrganizationMemberResponse, type OrganizationMemberTableRow, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type WithUserItemRequestBuilder, WithUserItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizations/me/members
 */
export interface MembersRequestBuilder extends BaseRequestBuilder<MembersRequestBuilder> {
    /**
     * Gets an item from the leadping.organizations.me.members.item collection
     * @param userId The ID of the user whose current-organization role is changing.
     * @returns {WithUserItemRequestBuilder}
     */
     byUserId(userId: string) : WithUserItemRequestBuilder;
    /**
     * Lists users assigned to the current organization, including roles and membership details for access management.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrganizationMemberTableRow[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationMemberTableRow[] | undefined>;
    /**
     * Adds an existing user to the current organization with the requested role for shared lead communication and account access.
     * @param body Request schema for the Leadping API organization user request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OrganizationMemberResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     */
     post(body: OrganizationMemberRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OrganizationMemberResponse | undefined>;
    /**
     * Lists users assigned to the current organization, including roles and membership details for access management.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Adds an existing user to the current organization with the requested role for shared lead communication and account access.
     * @param body Request schema for the Leadping API organization user request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OrganizationMemberRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MembersRequestBuilderUriTemplate = "{+baseurl}/organizations/me/members";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MembersRequestBuilderNavigationMetadata: Record<Exclude<keyof MembersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byUserId: {
        requestsMetadata: WithUserItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["userId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MembersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MembersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createOrganizationMemberTableRowFromDiscriminatorValue,
    },
    post: {
        uriTemplate: MembersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOrganizationMemberResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOrganizationMemberRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
