/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithLeadItemRequestBuilder, WithLeadItemRequestBuilderNavigationMetadata, WithLeadItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /dispositions/lead
 */
export interface LeadRequestBuilder extends BaseRequestBuilder<LeadRequestBuilder> {
    /**
     * Gets an item from the leadping.dispositions.lead.item collection
     * @param leadId The ID of the lead to get dispositions for.
     * @returns {WithLeadItemRequestBuilder}
     */
     byLeadId(leadId: string) : WithLeadItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LeadRequestBuilderUriTemplate = "{+baseurl}/dispositions/lead";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadRequestBuilderNavigationMetadata: Record<Exclude<keyof LeadRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLeadId: {
        requestsMetadata: WithLeadItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithLeadItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["leadId"],
    },
};
/* tslint:enable */
/* eslint-enable */
