/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNotificationResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type NotificationResponse, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { MarkReadRequestBuilderRequestsMetadata, type MarkReadRequestBuilder } from './markRead/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /notifications/{id}
 */
export interface NotificationsItemRequestBuilder extends BaseRequestBuilder<NotificationsItemRequestBuilder> {
    /**
     * The markRead property
     */
    get markRead(): MarkReadRequestBuilder;
    /**
     * Gets one notification for the current user and business.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NotificationResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NotificationResponse | undefined>;
    /**
     * Gets one notification for the current user and business.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NotificationsItemRequestBuilderUriTemplate = "{+baseurl}/notifications/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NotificationsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof NotificationsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    markRead: {
        requestsMetadata: MarkReadRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const NotificationsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: NotificationsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNotificationResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
