/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPhoneNumberResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePhoneNumberRequest, serializePhoneNumberResponse, type PhoneNumberRequest, type PhoneNumberResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { IsAvailableForPurchaseRequestBuilderRequestsMetadata, type IsAvailableForPurchaseRequestBuilder } from './isAvailableForPurchase/index.js';
// @ts-ignore
import { PhoneNumberItemRequestBuilderNavigationMetadata, PhoneNumberItemRequestBuilderRequestsMetadata, type PhoneNumberItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { OutgoingRequestBuilderNavigationMetadata, type OutgoingRequestBuilder } from './outgoing/index.js';
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers
 */
export interface PhoneNumbersRequestBuilder extends BaseRequestBuilder<PhoneNumbersRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The isAvailableForPurchase property
     */
    get isAvailableForPurchase(): IsAvailableForPurchaseRequestBuilder;
    /**
     * The outgoing property
     */
    get outgoing(): OutgoingRequestBuilder;
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * Gets an item from the leadping.phoneNumbers.item collection
     * @param phoneNumberId The phone number identifier.
     * @returns {PhoneNumberItemRequestBuilder}
     */
     byPhoneNumberId(phoneNumberId: string) : PhoneNumberItemRequestBuilder;
    /**
     * Purchases or creates a phone number for the current business so it can be assigned to messaging, calls, and lead follow-up.
     * @param body Request payload for phone number.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PhoneNumberResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: PhoneNumberRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PhoneNumberResponse | undefined>;
    /**
     * Purchases or creates a phone number for the current business so it can be assigned to messaging, calls, and lead follow-up.
     * @param body Request payload for phone number.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PhoneNumberRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PhoneNumbersRequestBuilderUriTemplate = "{+baseurl}/phone-numbers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PhoneNumbersRequestBuilderNavigationMetadata: Record<Exclude<keyof PhoneNumbersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPhoneNumberId: {
        requestsMetadata: PhoneNumberItemRequestBuilderRequestsMetadata,
        navigationMetadata: PhoneNumberItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["phoneNumber%2Did"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    isAvailableForPurchase: {
        requestsMetadata: IsAvailableForPurchaseRequestBuilderRequestsMetadata,
    },
    outgoing: {
        navigationMetadata: OutgoingRequestBuilderNavigationMetadata,
    },
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PhoneNumbersRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PhoneNumbersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPhoneNumberResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePhoneNumberRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
