/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFeedbackResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeFeedbackCreateRequest, serializeFeedbackResponse, type FeedbackCreateRequest, type FeedbackResponse, type ProblemDetails } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /feedback
 */
export interface FeedbackRequestBuilder extends BaseRequestBuilder<FeedbackRequestBuilder> {
    /**
     * Creates product feedback for the current business, capturing category, message, and context for operator review.
     * @param body Request schema for the Leadping API feedback creation request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FeedbackResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: FeedbackCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FeedbackResponse | undefined>;
    /**
     * Creates product feedback for the current business, capturing category, message, and context for operator review.
     * @param body Request schema for the Leadping API feedback creation request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FeedbackCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FeedbackRequestBuilderUriTemplate = "{+baseurl}/feedback";
/**
 * Metadata for all the requests in the request builder.
 */
export const FeedbackRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FeedbackRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFeedbackResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFeedbackCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
