/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CancelRequestBuilderRequestsMetadata, type CancelRequestBuilder } from './cancel/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sms/{smsEventId}
 */
export interface WithSmsEventItemRequestBuilder extends BaseRequestBuilder<WithSmsEventItemRequestBuilder> {
    /**
     * The cancel property
     */
    get cancel(): CancelRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithSmsEventItemRequestBuilderUriTemplate = "{+baseurl}/sms/{smsEventId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSmsEventItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSmsEventItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cancel: {
        requestsMetadata: CancelRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
