/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/sms/all
 */
export interface AllRequestBuilder extends BaseRequestBuilder<AllRequestBuilder> {
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AllRequestBuilderUriTemplate = "{+baseurl}/events/sms/all";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AllRequestBuilderNavigationMetadata: Record<Exclude<keyof AllRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
