/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTokenItemRequestBuilder, WithTokenItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses/invitations/token
 */
export interface TokenRequestBuilder extends BaseRequestBuilder<TokenRequestBuilder> {
    /**
     * Gets an item from the leadping.businesses.invitations.token.item collection
     * @param token The invitation acceptance token.
     * @returns {WithTokenItemRequestBuilder}
     */
     byToken(token: string) : WithTokenItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TokenRequestBuilderUriTemplate = "{+baseurl}/businesses/invitations/token";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TokenRequestBuilderNavigationMetadata: Record<Exclude<keyof TokenRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byToken: {
        requestsMetadata: WithTokenItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["token"],
    },
};
/* tslint:enable */
/* eslint-enable */
