/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadStatusResponseFromDiscriminatorValue, serializeLeadStatusRequest, serializeLeadStatusResponse, type LeadStatusRequest, type LeadStatusResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /lead-statuses/{id}
 */
export interface LeadStatusesItemRequestBuilder extends BaseRequestBuilder<LeadStatusesItemRequestBuilder> {
    /**
     * Archive
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<boolean>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<boolean | undefined>;
    /**
     * Update
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadStatusResponse>}
     */
     put(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadStatusResponse | undefined>;
    /**
     * Archive
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Update
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: LeadStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LeadStatusesItemRequestBuilderUriTemplate = "{+baseurl}/lead-statuses/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const LeadStatusesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: LeadStatusesItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "boolean",
    },
    put: {
        uriTemplate: LeadStatusesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createLeadStatusResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadStatusRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
