/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfPhoneNumberTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfPhoneNumberTableRow, serializeRequestDataOptions, type PagedResultOfPhoneNumberTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/all/organization
 */
export interface OrganizationRequestBuilder extends BaseRequestBuilder<OrganizationRequestBuilder> {
    /**
     * Lists phone numbers visible to the current organization with paging, sorting, and filters for messaging, calling, and warmup management.
     * @param body Defines cursor pagination, sorting, search, exact-match filters, and range filters for a structured API query.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfPhoneNumberTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfPhoneNumberTableRow | undefined>;
    /**
     * Lists phone numbers visible to the current organization with paging, sorting, and filters for messaging, calling, and warmup management.
     * @param body Defines cursor pagination, sorting, search, exact-match filters, and range filters for a structured API query.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrganizationRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/all/organization";
/**
 * Metadata for all the requests in the request builder.
 */
export const OrganizationRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: OrganizationRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfPhoneNumberTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
