/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createWalletResponseFromDiscriminatorValue, type ProblemDetails, type WalletResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /wallets/{id}
 */
export interface WalletsItemRequestBuilder extends BaseRequestBuilder<WalletsItemRequestBuilder> {
    /**
     * Returns one wallet by ID, including balance, billing context, and funding status for account payment workflows.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WalletResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WalletResponse | undefined>;
    /**
     * Returns one wallet by ID, including balance, billing context, and funding status for account payment workflows.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WalletsItemRequestBuilderUriTemplate = "{+baseurl}/wallets/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WalletsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WalletsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWalletResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
