/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSourceMetricsResponseFromDiscriminatorValue, type ProblemDetails, type SourceMetricsResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sources/{id}/metrics
 */
export interface MetricsRequestBuilder extends BaseRequestBuilder<MetricsRequestBuilder> {
    /**
     * Returns lead creation metrics for one business intake source, including accepted, rejected, duplicate, validation, and recent activity counts for monitoring.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SourceMetricsResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<MetricsRequestBuilderGetQueryParameters> | undefined) : Promise<SourceMetricsResponse | undefined>;
    /**
     * Returns lead creation metrics for one business intake source, including accepted, rejected, duplicate, validation, and recent activity counts for monitoring.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MetricsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns lead creation metrics for one business intake source, including accepted, rejected, duplicate, validation, and recent activity counts for monitoring.
 */
export interface MetricsRequestBuilderGetQueryParameters {
    /**
     * Optional rolling day count when explicit dates are not provided.
     */
    days?: number;
    /**
     * Optional end date/time for the metric range.
     */
    endAt?: Date;
    /**
     * Optional start date/time for the metric range.
     */
    startAt?: Date;
}
/**
 * Uri template for the request builder.
 */
export const MetricsRequestBuilderUriTemplate = "{+baseurl}/sources/{id}/metrics{?days*,endAt*,startAt*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MetricsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MetricsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSourceMetricsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
