/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUserResponseFromDiscriminatorValue, serializeChangeBillingPlanRequest, serializeUserResponse, type ChangeBillingPlanRequest, type ProblemDetails, type UserResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/change-billing-plan
 */
export interface ChangeBillingPlanRequestBuilder extends BaseRequestBuilder<ChangeBillingPlanRequestBuilder> {
    /**
     * Changes the current user's billing plan selection, updating account billing state and plan-specific capabilities.
     * @param body Request payload for change billing plan.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     put(body: ChangeBillingPlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserResponse | undefined>;
    /**
     * Changes the current user's billing plan selection, updating account billing state and plan-specific capabilities.
     * @param body Request payload for change billing plan.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ChangeBillingPlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChangeBillingPlanRequestBuilderUriTemplate = "{+baseurl}/users/change-billing-plan";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChangeBillingPlanRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ChangeBillingPlanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChangeBillingPlanRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
