/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAutomationConsoleResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type AutomationConsoleResponse, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /automations/{id}/runs/{runId}
 */
export interface WithRunItemRequestBuilder extends BaseRequestBuilder<WithRunItemRequestBuilder> {
    /**
     * Returns the specified persisted execution run for an automation in the current organization, including its current console state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AutomationConsoleResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AutomationConsoleResponse | undefined>;
    /**
     * Returns the specified persisted execution run for an automation in the current organization, including its current console state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRunItemRequestBuilderUriTemplate = "{+baseurl}/automations/{id}/runs/{runId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRunItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithRunItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAutomationConsoleResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
