/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createTransactionResponseFromDiscriminatorValue, type ProblemDetails, type TransactionResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /transactions/{id}
 */
export interface TransactionsItemRequestBuilder extends BaseRequestBuilder<TransactionsItemRequestBuilder> {
    /**
     * Returns one transaction visible to the current user, including amount, status, wallet context, and billing metadata.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TransactionResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TransactionResponse | undefined>;
    /**
     * Returns one transaction visible to the current user, including amount, status, wallet context, and billing metadata.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TransactionsItemRequestBuilderUriTemplate = "{+baseurl}/transactions/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const TransactionsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TransactionsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTransactionResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
