/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PaymentMethodsItemRequestBuilderRequestsMetadata, type PaymentMethodsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payment-methods
 */
export interface PaymentMethodsRequestBuilder extends BaseRequestBuilder<PaymentMethodsRequestBuilder> {
    /**
     * Gets an item from the leadping.paymentMethods.item collection
     * @param id The ID of the payment method to retrieve.
     * @returns {PaymentMethodsItemRequestBuilder}
     */
     byId(id: string) : PaymentMethodsItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PaymentMethodsRequestBuilderUriTemplate = "{+baseurl}/payment-methods";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PaymentMethodsRequestBuilderNavigationMetadata: Record<Exclude<keyof PaymentMethodsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PaymentMethodsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
