/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOutgoingNumberSelectionResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeOutgoingNumberManualOverrideRequest, serializeOutgoingNumberSelectionResponse, type OutgoingNumberManualOverrideRequest, type OutgoingNumberSelectionResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/outgoing/manual-override
 */
export interface ManualOverrideRequestBuilder extends BaseRequestBuilder<ManualOverrideRequestBuilder> {
    /**
     * Validates a manual outgoing-number override before use, checking ownership, destination, and delivery eligibility.
     * @param body Request schema for the Leadping API outgoing number manual override request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingNumberSelectionResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: OutgoingNumberManualOverrideRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingNumberSelectionResponse | undefined>;
    /**
     * Validates a manual outgoing-number override before use, checking ownership, destination, and delivery eligibility.
     * @param body Request schema for the Leadping API outgoing number manual override request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OutgoingNumberManualOverrideRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ManualOverrideRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/outgoing/manual-override";
/**
 * Metadata for all the requests in the request builder.
 */
export const ManualOverrideRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ManualOverrideRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingNumberSelectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOutgoingNumberManualOverrideRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
