/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUserResponseFromDiscriminatorValue, serializeComplianceUpdateRequest, serializeUserResponse, type ComplianceUpdateRequest, type ProblemDetails, type UserResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/compliance
 */
export interface ComplianceRequestBuilder extends BaseRequestBuilder<ComplianceRequestBuilder> {
    /**
     * Updates current-user compliance settings used for messaging eligibility, billing readiness, and business account setup.
     * @param body Request payload for compliance update.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     put(body: ComplianceUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserResponse | undefined>;
    /**
     * Updates current-user compliance settings used for messaging eligibility, billing readiness, and business account setup.
     * @param body Request payload for compliance update.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ComplianceUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ComplianceRequestBuilderUriTemplate = "{+baseurl}/users/compliance";
/**
 * Metadata for all the requests in the request builder.
 */
export const ComplianceRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ComplianceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeComplianceUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
