/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfLeadStatusChangeResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfLeadStatusChangeResponse, serializeRequestDataOptions, type PagedResultOfLeadStatusChangeResponse, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /lead-status-changes/all/my
 */
export interface MyRequestBuilder extends BaseRequestBuilder<MyRequestBuilder> {
    /**
     * Returns a filtered, paginated history of lead status changes for the current organization for workflow analysis, reporting, and audit review.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfLeadStatusChangeResponse>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfLeadStatusChangeResponse | undefined>;
    /**
     * Returns a filtered, paginated history of lead status changes for the current organization for workflow analysis, reporting, and audit review.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MyRequestBuilderUriTemplate = "{+baseurl}/lead-status-changes/all/my";
/**
 * Metadata for all the requests in the request builder.
 */
export const MyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfLeadStatusChangeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
