/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFeedbackResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeFeedbackAdminUpdateRequest, serializeFeedbackResponse, type FeedbackAdminUpdateRequest, type FeedbackResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /feedback/admin/{id}
 */
export interface AdminItemRequestBuilder extends BaseRequestBuilder<AdminItemRequestBuilder> {
    /**
     * Returns one feedback item for admin triage, including business context, submitted details, status, and review fields.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FeedbackResponse>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FeedbackResponse | undefined>;
    /**
     * Updates admin triage fields on a feedback item, such as status, priority, notes, or reviewed metadata.
     * @param body Admin triage update request for product feedback.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FeedbackResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     put(body: FeedbackAdminUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FeedbackResponse | undefined>;
    /**
     * Returns one feedback item for admin triage, including business context, submitted details, status, and review fields.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates admin triage fields on a feedback item, such as status, priority, notes, or reviewed metadata.
     * @param body Admin triage update request for product feedback.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: FeedbackAdminUpdateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AdminItemRequestBuilderUriTemplate = "{+baseurl}/feedback/admin/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AdminItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AdminItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFeedbackResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: AdminItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFeedbackResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFeedbackAdminUpdateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
