/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { type WithCallEventItemRequestBuilder, WithCallEventItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { LeadRequestBuilderNavigationMetadata, type LeadRequestBuilder } from './lead/index.js';
// @ts-ignore
import { PhoneRequestBuilderNavigationMetadata, type PhoneRequestBuilder } from './phone/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/calls
 */
export interface CallsRequestBuilder extends BaseRequestBuilder<CallsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The lead property
     */
    get lead(): LeadRequestBuilder;
    /**
     * The phone property
     */
    get phone(): PhoneRequestBuilder;
    /**
     * Gets an item from the leadping.events.calls.item collection
     * @param callEventId The ID of the call event to retrieve.
     * @returns {WithCallEventItemRequestBuilder}
     */
     byCallEventId(callEventId: string) : WithCallEventItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CallsRequestBuilderUriTemplate = "{+baseurl}/events/calls";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CallsRequestBuilderNavigationMetadata: Record<Exclude<keyof CallsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCallEventId: {
        requestsMetadata: WithCallEventItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["callEventId"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    lead: {
        navigationMetadata: LeadRequestBuilderNavigationMetadata,
    },
    phone: {
        navigationMetadata: PhoneRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
