/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { HangupRequestBuilderRequestsMetadata, type HangupRequestBuilder } from './hangup/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { TransferRequestBuilderRequestsMetadata, type TransferRequestBuilder } from './transfer/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-call/{callId}
 */
export interface WithCallItemRequestBuilder extends BaseRequestBuilder<WithCallItemRequestBuilder> {
    /**
     * The hangup property
     */
    get hangup(): HangupRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
    /**
     * The transfer property
     */
    get transfer(): TransferRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithCallItemRequestBuilderUriTemplate = "{+baseurl}/phone-call/{callId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithCallItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithCallItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    hangup: {
        requestsMetadata: HangupRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
    transfer: {
        requestsMetadata: TransferRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
