/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOutgoingNumberSelectionResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeOutgoingNumberSelectionRequest, serializeOutgoingNumberSelectionResponse, type OutgoingNumberSelectionRequest, type OutgoingNumberSelectionResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/outgoing/new
 */
export interface NewRequestBuilder extends BaseRequestBuilder<NewRequestBuilder> {
    /**
     * Selects an outgoing phone number for a new outbound lead message using destination, source, and delivery eligibility rules.
     * @param body Request schema for the Leadping API outgoing number selection request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingNumberSelectionResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: OutgoingNumberSelectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingNumberSelectionResponse | undefined>;
    /**
     * Selects an outgoing phone number for a new outbound lead message using destination, source, and delivery eligibility rules.
     * @param body Request schema for the Leadping API outgoing number selection request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OutgoingNumberSelectionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NewRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/outgoing/new";
/**
 * Metadata for all the requests in the request builder.
 */
export const NewRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: NewRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingNumberSelectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOutgoingNumberSelectionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
