/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { ResendRequestBuilderRequestsMetadata, type ResendRequestBuilder } from './resend/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizations/me/invitations/{invitationId}
 */
export interface WithInvitationItemRequestBuilder extends BaseRequestBuilder<WithInvitationItemRequestBuilder> {
    /**
     * The resend property
     */
    get resend(): ResendRequestBuilder;
    /**
     * Revokes a pending current-organization invitation so the recipient can no longer use it to join the organization.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Revokes a pending current-organization invitation so the recipient can no longer use it to join the organization.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithInvitationItemRequestBuilderUriTemplate = "{+baseurl}/organizations/me/invitations/{invitationId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithInvitationItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithInvitationItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    resend: {
        requestsMetadata: ResendRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithInvitationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithInvitationItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/problem+json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
