/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createUserResponseFromDiscriminatorValue, serializeUserNotificationPreferences, serializeUserResponse, type ProblemDetails, type UserNotificationPreferences, type UserResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /users/me/notification-preferences
 */
export interface NotificationPreferencesRequestBuilder extends BaseRequestBuilder<NotificationPreferencesRequestBuilder> {
    /**
     * Replaces the notification channel and delivery preferences stored for the authenticated user.
     * @param body Describes user notification preferences data used in Leadping API requests and responses.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     put(body: UserNotificationPreferences, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserResponse | undefined>;
    /**
     * Replaces the notification channel and delivery preferences stored for the authenticated user.
     * @param body Describes user notification preferences data used in Leadping API requests and responses.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UserNotificationPreferences, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NotificationPreferencesRequestBuilderUriTemplate = "{+baseurl}/users/me/notification-preferences";
/**
 * Metadata for all the requests in the request builder.
 */
export const NotificationPreferencesRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: NotificationPreferencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUserNotificationPreferences,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
