/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /.well-known/agent-card.json
 */
export interface AgentCardJsonRequestBuilder extends BaseRequestBuilder<AgentCardJsonRequestBuilder> {
    /**
     * Returns Leadping's public A2A Agent Card, including protocol capabilities, authentication requirements, input and output modes, and supported skills.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Returns Leadping's public A2A Agent Card, including protocol capabilities, authentication requirements, input and output modes, and supported skills.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AgentCardJsonRequestBuilderUriTemplate = "{+baseurl}/.well-known/agent-card.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const AgentCardJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AgentCardJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
