/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { CallsRequestBuilderNavigationMetadata, type CallsRequestBuilder } from './calls/index.js';
// @ts-ignore
import { ConversationsRequestBuilderNavigationMetadata, type ConversationsRequestBuilder } from './conversations/index.js';
// @ts-ignore
import { DetailRequestBuilderNavigationMetadata, type DetailRequestBuilder } from './detail/index.js';
// @ts-ignore
import { type WithEventItemRequestBuilder, WithEventItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { LeadsRequestBuilderNavigationMetadata, type LeadsRequestBuilder } from './leads/index.js';
// @ts-ignore
import { OrganizationsRequestBuilderNavigationMetadata, type OrganizationsRequestBuilder } from './organizations/index.js';
// @ts-ignore
import { SmsRequestBuilderNavigationMetadata, type SmsRequestBuilder } from './sms/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events
 */
export interface EventsRequestBuilder extends BaseRequestBuilder<EventsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The calls property
     */
    get calls(): CallsRequestBuilder;
    /**
     * The conversations property
     */
    get conversations(): ConversationsRequestBuilder;
    /**
     * The detail property
     */
    get detail(): DetailRequestBuilder;
    /**
     * The leads property
     */
    get leads(): LeadsRequestBuilder;
    /**
     * The organizations property
     */
    get organizations(): OrganizationsRequestBuilder;
    /**
     * The sms property
     */
    get sms(): SmsRequestBuilder;
    /**
     * Gets an item from the leadping.events.item collection
     * @param eventId The ID of the event.
     * @returns {WithEventItemRequestBuilder}
     */
     byEventId(eventId: string) : WithEventItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EventsRequestBuilderUriTemplate = "{+baseurl}/events";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EventsRequestBuilderNavigationMetadata: Record<Exclude<keyof EventsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byEventId: {
        requestsMetadata: WithEventItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["eventId"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    calls: {
        navigationMetadata: CallsRequestBuilderNavigationMetadata,
    },
    conversations: {
        navigationMetadata: ConversationsRequestBuilderNavigationMetadata,
    },
    detail: {
        navigationMetadata: DetailRequestBuilderNavigationMetadata,
    },
    leads: {
        navigationMetadata: LeadsRequestBuilderNavigationMetadata,
    },
    organizations: {
        navigationMetadata: OrganizationsRequestBuilderNavigationMetadata,
    },
    sms: {
        navigationMetadata: SmsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
