/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiKeysItemRequestBuilderRequestsMetadata, type ApiKeysItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { MyRequestBuilderRequestsMetadata, type MyRequestBuilder } from './my/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizations/api-keys
 */
export interface ApiKeysRequestBuilder extends BaseRequestBuilder<ApiKeysRequestBuilder> {
    /**
     * The my property
     */
    get my(): MyRequestBuilder;
    /**
     * Gets an item from the leadping.organizations.apiKeys.item collection
     * @param id Unique identifier of the item
     * @returns {ApiKeysItemRequestBuilder}
     */
     byId(id: string) : ApiKeysItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiKeysRequestBuilderUriTemplate = "{+baseurl}/organizations/api-keys";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiKeysRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiKeysRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ApiKeysItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    my: {
        requestsMetadata: MyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
