/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSuppressionEntryResponseFromDiscriminatorValue, serializeSuppressionEntryRequest, serializeSuppressionEntryResponse, type ProblemDetails, type SuppressionEntryRequest, type SuppressionEntryResponse } from '../models/index.js';
// @ts-ignore
import { CheckRequestBuilderRequestsMetadata, type CheckRequestBuilder } from './check/index.js';
// @ts-ignore
import { ReleaseRequestBuilderRequestsMetadata, type ReleaseRequestBuilder } from './release/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /suppressions
 */
export interface SuppressionsRequestBuilder extends BaseRequestBuilder<SuppressionsRequestBuilder> {
    /**
     * The check property
     */
    get check(): CheckRequestBuilder;
    /**
     * The release property
     */
    get release(): ReleaseRequestBuilder;
    /**
     * The suppression entry response was created successfully.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuppressionEntryResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuppressionEntryResponse | undefined>;
    /**
     * The suppression entry response was created successfully.
     * @param body Request payload for suppression entry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SuppressionEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SuppressionsRequestBuilderUriTemplate = "{+baseurl}/suppressions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SuppressionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SuppressionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    check: {
        requestsMetadata: CheckRequestBuilderRequestsMetadata,
    },
    release: {
        requestsMetadata: ReleaseRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SuppressionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SuppressionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuppressionEntryResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSuppressionEntryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
