/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfLeadTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfLeadTableRow, serializeRequestDataOptions, type PagedResultOfLeadTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /leads/all/my
 */
export interface MyRequestBuilder extends BaseRequestBuilder<MyRequestBuilder> {
    /**
     * Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfLeadTableRow>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : Promise<PagedResultOfLeadTableRow | undefined>;
    /**
     * Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<MyRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
 */
export interface MyRequestBuilderPostQueryParameters {
    archiveFilter?: string;
    tagIds?: string[];
    tagMatchAll?: boolean;
    untagged?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const MyRequestBuilderUriTemplate = "{+baseurl}/leads/all/my{?archiveFilter*,tagIds*,tagMatchAll*,untagged*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const MyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfLeadTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
