/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInvoicePdfAccessResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type InvoicePdfAccessResponse, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /payment-methods/invoices/{invoiceId}/pdf-access
 */
export interface PdfAccessRequestBuilder extends BaseRequestBuilder<PdfAccessRequestBuilder> {
    /**
     * Creates a short-lived URL for viewing or downloading a private invoice PDF.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InvoicePdfAccessResponse>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<PdfAccessRequestBuilderGetQueryParameters> | undefined) : Promise<InvoicePdfAccessResponse | undefined>;
    /**
     * Creates a short-lived URL for viewing or downloading a private invoice PDF.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PdfAccessRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Creates a short-lived URL for viewing or downloading a private invoice PDF.
 */
export interface PdfAccessRequestBuilderGetQueryParameters {
    download?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const PdfAccessRequestBuilderUriTemplate = "{+baseurl}/payment-methods/invoices/{invoiceId}/pdf-access{?download*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PdfAccessRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PdfAccessRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInvoicePdfAccessResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
