/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfEventTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfEventTableRow, serializeRequestDataOptions, type PagedResultOfEventTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/leads/{leadId}
 */
export interface WithLeadItemRequestBuilder extends BaseRequestBuilder<WithLeadItemRequestBuilder> {
    /**
     * Lists event records for one lead with paging, covering communication, routing, automation, and event changes.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfEventTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfEventTableRow | undefined>;
    /**
     * Lists event records for one lead with paging, covering communication, routing, automation, and event changes.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithLeadItemRequestBuilderUriTemplate = "{+baseurl}/events/leads/{leadId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLeadItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithLeadItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfEventTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
