/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiKeysRequestBuilderNavigationMetadata, type ApiKeysRequestBuilder } from './apiKeys/index.js';
// @ts-ignore
import { MeRequestBuilderNavigationMetadata, MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /organizations
 */
export interface OrganizationsRequestBuilder extends BaseRequestBuilder<OrganizationsRequestBuilder> {
    /**
     * The apiKeys property
     */
    get apiKeys(): ApiKeysRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrganizationsRequestBuilderUriTemplate = "{+baseurl}/organizations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrganizationsRequestBuilderNavigationMetadata: Record<Exclude<keyof OrganizationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    apiKeys: {
        navigationMetadata: ApiKeysRequestBuilderNavigationMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
        navigationMetadata: MeRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
