/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPagedResultOfPhoneNumberTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePagedResultOfPhoneNumberTableRow, serializeRequestDataOptions, type PagedResultOfPhoneNumberTableRow, type ProblemDetails, type RequestDataOptions } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/all/business
 */
export interface BusinessRequestBuilder extends BaseRequestBuilder<BusinessRequestBuilder> {
    /**
     * Lists phone numbers visible to the current business with paging, sorting, and filters for messaging, calling, and warmup management.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PagedResultOfPhoneNumberTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PagedResultOfPhoneNumberTableRow | undefined>;
    /**
     * Lists phone numbers visible to the current business with paging, sorting, and filters for messaging, calling, and warmup management.
     * @param body Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RequestDataOptions, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BusinessRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/all/business";
/**
 * Metadata for all the requests in the request builder.
 */
export const BusinessRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BusinessRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPagedResultOfPhoneNumberTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRequestDataOptions,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
