/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSmsResponseFromDiscriminatorValue, serializeSendSmsRequest, serializeSmsResponse, type ProblemDetails, type SendSmsRequest, type SmsResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sms/send
 */
export interface SendRequestBuilder extends BaseRequestBuilder<SendRequestBuilder> {
    /**
     * Sends an SMS message to a lead or phone number, applying current-business sender selection, scheduling, and delivery rules.
     * @param body Request schema for the Leadping API SMS send request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SmsResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: SendSmsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SmsResponse | undefined>;
    /**
     * Sends an SMS message to a lead or phone number, applying current-business sender selection, scheduling, and delivery rules.
     * @param body Request schema for the Leadping API SMS send request, including the fields clients can send.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SendSmsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SendRequestBuilderUriTemplate = "{+baseurl}/sms/send";
/**
 * Metadata for all the requests in the request builder.
 */
export const SendRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SendRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSmsResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSendSmsRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
