/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { type WithSmsEventItemRequestBuilder, WithSmsEventItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { LeadRequestBuilderNavigationMetadata, type LeadRequestBuilder } from './lead/index.js';
// @ts-ignore
import { PhoneRequestBuilderNavigationMetadata, type PhoneRequestBuilder } from './phone/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/sms
 */
export interface SmsRequestBuilder extends BaseRequestBuilder<SmsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The lead property
     */
    get lead(): LeadRequestBuilder;
    /**
     * The phone property
     */
    get phone(): PhoneRequestBuilder;
    /**
     * Gets an item from the leadping.events.sms.item collection
     * @param smsEventId The ID of the SMS event to retrieve.
     * @returns {WithSmsEventItemRequestBuilder}
     */
     bySmsEventId(smsEventId: string) : WithSmsEventItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SmsRequestBuilderUriTemplate = "{+baseurl}/events/sms";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SmsRequestBuilderNavigationMetadata: Record<Exclude<keyof SmsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySmsEventId: {
        requestsMetadata: WithSmsEventItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["smsEventId"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    lead: {
        navigationMetadata: LeadRequestBuilderNavigationMetadata,
    },
    phone: {
        navigationMetadata: PhoneRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
