/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OrganizationRequestBuilderRequestsMetadata, type OrganizationRequestBuilder } from './organization/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/all
 */
export interface AllRequestBuilder extends BaseRequestBuilder<AllRequestBuilder> {
    /**
     * The organization property
     */
    get organization(): OrganizationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AllRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/all";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AllRequestBuilderNavigationMetadata: Record<Exclude<keyof AllRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    organization: {
        requestsMetadata: OrganizationRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
