/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BusinessRequestBuilderRequestsMetadata, type BusinessRequestBuilder } from './business/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/all
 */
export interface AllRequestBuilder extends BaseRequestBuilder<AllRequestBuilder> {
    /**
     * The business property
     */
    get business(): BusinessRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AllRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/all";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AllRequestBuilderNavigationMetadata: Record<Exclude<keyof AllRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    business: {
        requestsMetadata: BusinessRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
