/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEventTableRowFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeCreateNoteRequest, serializeEventTableRow, type CreateNoteRequest, type EventTableRow, type ProblemDetails } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /events/conversations/{conversationId}/notes
 */
export interface NotesRequestBuilder extends BaseRequestBuilder<NotesRequestBuilder> {
    /**
     * Creates a note event on a conversation so users can document lead context, handoffs, and follow-up details.
     * @param body Request payload for create note.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EventTableRow>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateNoteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EventTableRow | undefined>;
    /**
     * Creates a note event on a conversation so users can document lead context, handoffs, and follow-up details.
     * @param body Request payload for create note.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateNoteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NotesRequestBuilderUriTemplate = "{+baseurl}/events/conversations/{conversationId}/notes";
/**
 * Metadata for all the requests in the request builder.
 */
export const NotesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: NotesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEventTableRowFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateNoteRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
