/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessSwitchOptionFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type BusinessSwitchOption, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /businesses/me/options
 */
export interface OptionsRequestBuilder extends BaseRequestBuilder<OptionsRequestBuilder> {
    /**
     * Lists businesses the authenticated user can switch into, including membership role and current-business selection data.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BusinessSwitchOption[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BusinessSwitchOption[] | undefined>;
    /**
     * Lists businesses the authenticated user can switch into, including membership role and current-business selection data.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OptionsRequestBuilderUriTemplate = "{+baseurl}/businesses/me/options";
/**
 * Metadata for all the requests in the request builder.
 */
export const OptionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OptionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBusinessSwitchOptionFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
