/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { LeadStatusChangesItemRequestBuilderRequestsMetadata, type LeadStatusChangesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /lead-status-changes
 */
export interface LeadStatusChangesRequestBuilder extends BaseRequestBuilder<LeadStatusChangesRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * Gets an item from the leadping.leadStatusChanges.item collection
     * @param id The ID of the lead status change.
     * @returns {LeadStatusChangesItemRequestBuilder}
     */
     byId(id: string) : LeadStatusChangesItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LeadStatusChangesRequestBuilderUriTemplate = "{+baseurl}/lead-status-changes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LeadStatusChangesRequestBuilderNavigationMetadata: Record<Exclude<keyof LeadStatusChangesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LeadStatusChangesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
