/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLeadResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeLeadAssignmentRequest, serializeLeadResponse, type LeadAssignmentRequest, type LeadResponse, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /leads/{-id}/assignment
 */
export interface AssignmentRequestBuilder extends BaseRequestBuilder<AssignmentRequestBuilder> {
    /**
     * Updates ownership of the specified lead after validating that the selected assignee is an active member of the current organization.
     * @param body Assigns an organization lead to an active organization member. A null user ID returns the lead to the unassigned queue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LeadResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 429 status code
     */
     put(body: LeadAssignmentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LeadResponse | undefined>;
    /**
     * Updates ownership of the specified lead after validating that the selected assignee is an active member of the current organization.
     * @param body Assigns an organization lead to an active organization member. A null user ID returns the lead to the unassigned queue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: LeadAssignmentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AssignmentRequestBuilderUriTemplate = "{+baseurl}/leads/{%2Did}/assignment";
/**
 * Metadata for all the requests in the request builder.
 */
export const AssignmentRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: AssignmentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLeadResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLeadAssignmentRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
