/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOutgoingNumberSelectionResponseFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializeOutgoingNumberManualOverrideRequest, serializeOutgoingNumberSelectionResponse, type OutgoingNumberManualOverrideRequest, type OutgoingNumberSelectionResponse, type ProblemDetails } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /phone-numbers/outgoing/conversation/{conversationId}/override
 */
export interface OverrideRequestBuilder extends BaseRequestBuilder<OverrideRequestBuilder> {
    /**
     * Clears a conversation's outgoing-number override so future lead messages return to automatic number selection.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingNumberSelectionResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingNumberSelectionResponse | undefined>;
    /**
     * Sets the outgoing phone number override for a conversation so future lead messages use the selected eligible number.
     * @param body Request payload for outgoing number manual override.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingNumberSelectionResponse>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(body: OutgoingNumberManualOverrideRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingNumberSelectionResponse | undefined>;
    /**
     * Clears a conversation's outgoing-number override so future lead messages return to automatic number selection.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Sets the outgoing phone number override for a conversation so future lead messages use the selected eligible number.
     * @param body Request payload for outgoing number manual override.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OutgoingNumberManualOverrideRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OverrideRequestBuilderUriTemplate = "{+baseurl}/phone-numbers/outgoing/conversation/{conversationId}/override";
/**
 * Metadata for all the requests in the request builder.
 */
export const OverrideRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: OverrideRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingNumberSelectionResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: OverrideRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingNumberSelectionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOutgoingNumberManualOverrideRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
